// Generated by tools/lessons_gen.py; validated with python-chess. / tools/lessons_gen.pyで自動生成し、python-chessで検証済み。
// All annotations are original. / 解説はすべて独自に書き下ろし。
const LESSONS = [
 {
  "id": "op_italian",
  "cat": "opening",
  "title": "イタリアン・ゲーム",
  "fen": null,
  "intro": "最も古く分かりやすい出だしの一つ。『中央を取る・軽い駒を素早く出す・キングを早く囲う』という開幕の三原則を自然に学べます。",
  "takeaway": "開幕は駒得より『展開の速さ』と『中央』。f7の弱点を意識してビショップとナイトを働かせる。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取り、ビショップとクイーンの道を開ける王道の第一手。"
   },
   {
    "san": "e5",
    "note": "黒も中央で張り合う。"
   },
   {
    "san": "Nf3",
    "note": "e5に当てながらナイトを展開。攻めと展開を兼ねる好手。"
   },
   {
    "san": "Nc6",
    "note": "ポーンを守りつつ展開。理想的な受け。"
   },
   {
    "san": "Bc4",
    "note": "相手の一番弱いf7の地点をにらむ位置にビショップを出す。これがイタリアン。"
   },
   {
    "san": "Bc5",
    "note": "黒も対称にf2をにらむ。"
   },
   {
    "san": "c3",
    "note": "次にd4で中央を広げる準備。ビショップの退路も確保。"
   },
   {
    "san": "Nf6",
    "note": "e4に当てて反撃しつつ展開。"
   },
   {
    "san": "d3",
    "note": "中央を静かに支え、じっくり駒を組み上げる現代的な指し方。"
   },
   {
    "san": "d6",
    "note": "黒も中央を固め、キングの安全を優先する。両者とも原則通りの好形。"
   }
  ],
  "en": {
   "title": "Italian Game",
   "intro": "One of the oldest and clearest openings. It naturally teaches three opening principles: fight for the center, develop minor pieces, and castle early.",
   "takeaway": "In the opening, prioritize development and the center over grabbing material. Keep an eye on the weakness of f7 and make the bishop and knight work.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes space in the center and opens the bishop and queen's diagonals."
    },
    {
     "san": "e5",
     "note": "Black also contests the center."
    },
    {
     "san": "Nf3",
     "note": "The knight develops with tempo against e5, combining pressure with development."
    },
    {
     "san": "Nc6",
     "note": "The pawn is defended while Black develops a piece."
    },
    {
     "san": "Bc4",
     "note": "The bishop eyes the vulnerable f7 square. This move gives the Italian Game its name."
    },
    {
     "san": "Bc5",
     "note": "Black mirrors the idea by eyeing f2."
    },
    {
     "san": "c3",
     "note": "Preparing d4 to expand in the center and giving the bishop a retreat square."
    },
    {
     "san": "Nf6",
     "note": "Black attacks e4 while developing."
    },
    {
     "san": "d3",
     "note": "White supports the center and chooses a calm setup."
    },
    {
     "san": "d6",
     "note": "Black reinforces the center and prepares for king safety. Both sides have followed sound principles."
    }
   ]
  }
 },
 {
  "id": "op_ruylopez",
  "cat": "opening",
  "title": "ルイ・ロペス(スパニッシュ)",
  "fen": null,
  "intro": "百年以上プロが指し続ける最重要オープニング。ビショップで相手のナイトに間接的な圧力をかけ、じわじわと中央の主導権を握ります。",
  "takeaway": "駒はすぐ取りにいかず『圧力』をかけて相手を窮屈にする。キングを早く囲い、その後に中央で戦う。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e5",
    "note": "対称に応じる。"
   },
   {
    "san": "Nf3",
    "note": "e5に当てて展開。"
   },
   {
    "san": "Nc6",
    "note": "守る。"
   },
   {
    "san": "Bb5",
    "note": "e5を守るナイトを間接的に狙う。すぐ取らず圧力をかけるのがロペスの思想。"
   },
   {
    "san": "a6",
    "note": "ビショップに態度を問う定番の一手。"
   },
   {
    "san": "Ba4",
    "note": "ピンを保ったまま退く。まだ交換しない。"
   },
   {
    "san": "Nf6",
    "note": "e4に当てて展開。中央への反撃を始める。"
   },
   {
    "san": "O-O",
    "note": "キングを早く安全にする。原則に忠実。"
   },
   {
    "san": "Be7",
    "note": "黒も展開し、次のキャスリングを用意。両者好形の主流形。"
   }
  ],
  "en": {
   "title": "Ruy Lopez (Spanish Opening)",
   "intro": "A major opening that has been played at the highest level for generations. The bishop creates indirect pressure on the knight defending e5, building central control over time.",
   "takeaway": "Do not rush to capture. Build pressure, castle, and then contest the center.",
   "moves": [
    {
     "san": "e4",
     "note": "White claims central space."
    },
    {
     "san": "e5",
     "note": "Black answers symmetrically."
    },
    {
     "san": "Nf3",
     "note": "The knight attacks e5 while developing."
    },
    {
     "san": "Nc6",
     "note": "Black defends e5 and develops."
    },
    {
     "san": "Bb5",
     "note": "The bishop puts indirect pressure on the knight defending e5. The point is pressure, not an immediate capture."
    },
    {
     "san": "a6",
     "note": "A standard move that asks the bishop to decide where it belongs."
    },
    {
     "san": "Ba4",
     "note": "The bishop retreats while keeping the pressure on the knight."
    },
    {
     "san": "Nf6",
     "note": "Black attacks e4 and begins active counterplay in the center."
    },
    {
     "san": "O-O",
     "note": "White castles early, following a core opening principle."
    },
    {
     "san": "Be7",
     "note": "Black develops and prepares to castle. This is a typical healthy position for both sides."
    }
   ]
  }
 },
 {
  "id": "op_sicilian",
  "cat": "opening",
  "title": "シチリアン・ディフェンス",
  "fen": null,
  "intro": "黒がe5と対称にせず、c5で『非対称』の戦いを挑む最も人気の高い応手。左右で攻める方向が分かれ、激しい戦いになりやすいのが特徴です。",
  "takeaway": "対称に受けるだけが正解ではない。あえて形を崩し、自分の攻め筋(黒はc列)を作りにいく考え方。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "c5",
    "note": "シチリアン。e5とせず、c列を開いて反撃の土台を作る。"
   },
   {
    "san": "Nf3",
    "note": "展開しつつd4の準備。"
   },
   {
    "san": "d6",
    "note": "中央を支え、後のNf6やe5に備える柔軟な一手。"
   },
   {
    "san": "d4",
    "note": "中央を開いて主導権を取りにいく。"
   },
   {
    "san": "cxd4",
    "note": "白のポーンを取り、c列が黒の攻めの通り道になる。"
   },
   {
    "san": "Nxd4",
    "note": "ナイトで取り返し、中央の好位置に据える。"
   },
   {
    "san": "Nf6",
    "note": "e4に当てて展開。"
   },
   {
    "san": "Nc3",
    "note": "e4を守りつつ展開。互いに戦いの準備が整う。"
   },
   {
    "san": "a6",
    "note": "ナジョルフ変化。b5の展開とマス作りを見据えた柔らかい待ちの一手。"
   }
  ],
  "en": {
   "title": "Sicilian Defense",
   "intro": "Black avoids a symmetrical ...e5 and chooses ...c5 for an unbalanced fight. The sides often attack on different wings, which can lead to sharp play.",
   "takeaway": "Symmetry is not mandatory. Black accepts a different pawn structure to create counterplay on the c-file.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes central space."
    },
    {
     "san": "c5",
     "note": "Black chooses the Sicilian, using the c-pawn to create an unbalanced position."
    },
    {
     "san": "Nf3",
     "note": "Developing while preparing d4."
    },
    {
     "san": "d6",
     "note": "Black supports the center and keeps ...Nf6 or ...e5 available."
    },
    {
     "san": "d4",
     "note": "White opens the center to fight for the initiative."
    },
    {
     "san": "cxd4",
     "note": "Black exchanges and opens the c-file for future activity."
    },
    {
     "san": "Nxd4",
     "note": "The knight recaptures and occupies a strong central square."
    },
    {
     "san": "Nf6",
     "note": "Black attacks e4 while developing."
    },
    {
     "san": "Nc3",
     "note": "The knight supports e4 and completes the basic development setup."
    },
    {
     "san": "a6",
     "note": "This is the Najdorf move order: ...a6 prepares ...b5 and controls useful squares."
    }
   ]
  }
 },
 {
  "id": "op_french",
  "cat": "opening",
  "title": "フレンチ・ディフェンス",
  "fen": null,
  "intro": "黒がe6から中央にd5をぶつける堅実な守り。キングサイドは堅い反面、c8のビショップの活用が課題になる、長期戦向きの作戦です。",
  "takeaway": "がっちり守って相手の攻めを受け止め、中央や側面での反撃を狙う『受けて勝つ』考え方。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e6",
    "note": "フレンチ。次にd5でe4に挑む準備。堅実さが身上。"
   },
   {
    "san": "d4",
    "note": "中央を広げる。"
   },
   {
    "san": "d5",
    "note": "予定通り中央に当てて主導権を争う。"
   },
   {
    "san": "Nc3",
    "note": "d5に当ててe4を支える発展。"
   },
   {
    "san": "Nf6",
    "note": "e4にさらに当てて中央の緊張を高める。"
   },
   {
    "san": "Bg5",
    "note": "f6のナイトをクイーンd8に対してピンし、e4への圧力を和らげる。"
   },
   {
    "san": "Be7",
    "note": "ピンを外す準備をしつつ展開。"
   },
   {
    "san": "e5",
    "note": "中央を閉じて空間を確保。以後は互いの攻めの方向がはっきり分かれる。"
   },
   {
    "san": "Nfd7",
    "note": "ナイトを引いて、後のc5やf6での反撃に備える。フレンチらしい辛抱の一手。"
   }
  ],
  "en": {
   "title": "French Defense",
   "intro": "Black prepares ...d5 with ...e6, building a solid central challenge. The king side is sturdy, but the c8 bishop may need careful planning in a long game.",
   "takeaway": "Absorb the opponent's central pressure, then strike back in the center or on the wings.",
   "moves": [
    {
     "san": "e4",
     "note": "White claims the center."
    },
    {
     "san": "e6",
     "note": "The French Defense: Black prepares ...d5 against e4."
    },
    {
     "san": "d4",
     "note": "White expands in the center."
    },
    {
     "san": "d5",
     "note": "Black challenges the center as planned."
    },
    {
     "san": "Nc3",
     "note": "The knight supports e4 and adds pressure to d5."
    },
    {
     "san": "Nf6",
     "note": "Black attacks e4 and increases the central tension."
    },
    {
     "san": "Bg5",
     "note": "The bishop pins the f6 knight to the queen on d8 and reduces the pressure on e4."
    },
    {
     "san": "Be7",
     "note": "Black develops and prepares to break the pin with ...Be7."
    },
    {
     "san": "e5",
     "note": "White closes the center and gains space. The future attacking directions become clearer."
    },
    {
     "san": "Nfd7",
     "note": "The knight retreats, readying counterplay with ...c5 or ...f6. Patient defense is typical of the French."
    }
   ]
  }
 },
 {
  "id": "op_qgd",
  "cat": "opening",
  "title": "クイーンズ・ギャンビット(断らない形)",
  "fen": null,
  "intro": "e4ではなくd4から始める代表的な戦型。c4のポーンは『ギャンビット』と呼ばれますが本当のタダ捨てではなく、中央の主導権と引き換えの誘いです。",
  "takeaway": "サイドのポーンを餌に中央を広げる。取っても取らなくても、狙いは常に『中央の支配』。",
  "moves": [
   {
    "san": "d4",
    "note": "クイーン側のポーンで中央を取る、e4と並ぶ二大出だし。"
   },
   {
    "san": "d5",
    "note": "対称に中央を占める。"
   },
   {
    "san": "c4",
    "note": "d5に当てる。取らせても中央を大きく取り返せるという誘い。"
   },
   {
    "san": "e6",
    "note": "クイーンズ・ギャンビット・ディクラインド。c4を取らず、d5をがっちり支える堅実策。"
   },
   {
    "san": "Nc3",
    "note": "d5への圧力を増しつつ展開。"
   },
   {
    "san": "Nf6",
    "note": "中央を支えながら展開。"
   },
   {
    "san": "Bg5",
    "note": "f6のナイトにピンをかけ、d5の守りを間接的に揺さぶる。"
   },
   {
    "san": "Be7",
    "note": "ピンを外す準備。"
   },
   {
    "san": "e3",
    "note": "地味だがc1のビショップを既に活用済みで、キングの道を開ける堅実な一手。"
   },
   {
    "san": "O-O",
    "note": "黒はキングを安全にして長い戦いに備える。典型的な好形。"
   }
  ],
  "en": {
   "title": "Queen's Gambit Declined",
   "intro": "A major opening beginning with d4 rather than e4. The c4 pawn is offered as a gambit, but the point is to gain central influence, not simply to give away material.",
   "takeaway": "Offer a flank pawn to build central pressure. Whether Black accepts or declines, the strategic goal is control of the center.",
   "moves": [
    {
     "san": "d4",
     "note": "White takes central space with the queen's pawn."
    },
    {
     "san": "d5",
     "note": "Black occupies the center symmetrically."
    },
    {
     "san": "c4",
     "note": "The c-pawn challenges d5. White offers it in exchange for central pressure."
    },
    {
     "san": "e6",
     "note": "Black declines the gambit and supports d5 with ...e6."
    },
    {
     "san": "Nc3",
     "note": "White increases pressure on d5 while developing."
    },
    {
     "san": "Nf6",
     "note": "Black develops while supporting the center."
    },
    {
     "san": "Bg5",
     "note": "The bishop pins the f6 knight to the queen and indirectly pressures d5."
    },
    {
     "san": "Be7",
     "note": "Black prepares to break the pin."
    },
    {
     "san": "e3",
     "note": "White opens the f1 bishop's path and prepares to castle."
    },
    {
     "san": "O-O",
     "note": "Black castles and prepares for a long strategic battle. This is a typical solid setup."
    }
   ]
  }
 },
 {
  "id": "op_carokann",
  "cat": "opening",
  "title": "カロ・カン・ディフェンス",
  "fen": null,
  "intro": "c6から d5 とぶつける、フレンチに似てキングサイドがより軽い守り。c8のビショップを展開しやすいのが長所で、堅実さと安定感で人気です。",
  "takeaway": "守りを固めつつ、フレンチで苦労しがちなビショップを先に活用しておく、バランス重視の考え方。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "c6",
    "note": "カロ・カン。次のd5に備える。フレンチと違いビショップの道をふさがない。"
   },
   {
    "san": "d4",
    "note": "中央を広げる。"
   },
   {
    "san": "d5",
    "note": "中央に当てる。"
   },
   {
    "san": "Nc3",
    "note": "d5に当ててe4を支える。"
   },
   {
    "san": "dxe4",
    "note": "中央を交換し、形をはっきりさせる。"
   },
   {
    "san": "Nxe4",
    "note": "取り返してナイトを好位置に。"
   },
   {
    "san": "Bf5",
    "note": "問題になりがちなビショップを、閉じ込められる前に外へ出す。これがカロ・カンの利点。"
   },
   {
    "san": "Ng3",
    "note": "黒のビショップに当てて手を稼ぐ。"
   },
   {
    "san": "Bg6",
    "note": "ビショップを保つ。黒は堅実な好形を得て、じっくりした戦いに持ち込む。"
   }
  ],
  "en": {
   "title": "Caro-Kann Defense",
   "intro": "Black prepares ...d5 with ...c6. Like the French, it is solid, but the c8 bishop can usually develop outside the pawn chain more easily.",
   "takeaway": "Build a sound center while developing the bishop before it becomes restricted. The result is a balanced, resilient setup.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes the center."
    },
    {
     "san": "c6",
     "note": "The Caro-Kann: ...c6 prepares ...d5 without blocking the c8 bishop."
    },
    {
     "san": "d4",
     "note": "White expands in the center."
    },
    {
     "san": "d5",
     "note": "Black challenges the center."
    },
    {
     "san": "Nc3",
     "note": "The knight supports e4 and attacks d5."
    },
    {
     "san": "dxe4",
     "note": "Black exchanges in the center and clarifies the pawn structure."
    },
    {
     "san": "Nxe4",
     "note": "White recaptures with the knight and occupies a good square."
    },
    {
     "san": "Bf5",
     "note": "The bishop develops outside the pawn chain before it can become restricted. This is a key Caro-Kann idea."
    },
    {
     "san": "Ng3",
     "note": "The knight attacks the bishop and gains a tempo."
    },
    {
     "san": "Bg6",
     "note": "The bishop preserves itself. Black has a solid, playable position."
    }
   ]
  }
 },
 {
  "id": "cb_fork",
  "cat": "combo",
  "title": "フォーク(ナイトの二股)",
  "fen": "6k1/8/2q5/3N4/8/8/8/6K1 w - - 0 1",
  "intro": "ナイトは離れた場所にいる駒にも一手で同時に攻撃をかけやすい駒です。キングと大駒を一度に狙う『フォーク』は、最初に覚えたい代表的な戦術です。",
  "takeaway": "ナイトで『チェックをかけながら別の大駒も攻める』位置を探す。相手がチェックに対応している間に、もう一方の駒を取れることがあります。",
  "moves": [
   {
    "san": "Ne7+",
    "note": "ナイトがチェックをかけると同時に、c6のクイーンも攻めている二股。相手はチェックを受けるしかない。"
   },
   {
    "san": "Kh8",
    "note": "キングが逃げる。クイーンは見捨てるしかない。"
   },
   {
    "san": "Nxc6",
    "note": "クイーンを頂いて大戦果。これがナイトのフォークの威力。"
   }
  ],
  "en": {
   "title": "Knight Fork",
   "intro": "A knight can often attack widely separated targets in one move. A fork that checks the king and attacks a major piece is a classic first tactic to learn.",
   "takeaway": "Look for a knight move that gives check while attacking another valuable piece. The opponent must answer the check first, which may leave the other target exposed.",
   "moves": [
    {
     "san": "Ne7+",
     "note": "The knight gives check and attacks the queen on c6 at the same time: a fork."
    },
    {
     "san": "Kh8",
     "note": "The king moves; the queen cannot save itself in this line."
    },
    {
     "san": "Nxc6",
     "note": "White wins the queen. This is the power of a knight fork."
    }
   ]
  }
 },
 {
  "id": "cb_pin",
  "cat": "combo",
  "title": "ピン(釘づけ)を突く",
  "fen": "3k4/8/8/3n4/2P5/8/8/3RK3 w - - 0 1",
  "intro": "一直線上の駒が動くと、その後ろのキングが攻撃される状態を『ピン(釘づけ)』といいます。ピンされた駒は動きにくくなりますが、守られているとは限らないので、攻撃できるかを確認しましょう。",
  "takeaway": "ピンされた駒を見つけたら、まず本当に動けないか、守り駒があるかを確認する。そのうえでポーンや軽い駒を重ねて攻撃する。",
  "moves": [
   {
    "san": "cxd5",
    "note": "ルークに釘づけにされたナイトは動けない(動けばd8のキングが取られる)ので、ポーンでそのまま頂ける。守れない駒は取るが鉄則。"
   }
  ],
  "en": {
   "title": "Using a Pin",
   "intro": "A piece is pinned when moving it would expose the king to a line attack. A pinned piece is restricted, but it is not automatically undefended, so always check the whole position.",
   "takeaway": "When you find a pinned piece, verify that it really cannot move and count its defenders before attacking it with a pawn or minor piece.",
   "moves": [
    {
     "san": "cxd5",
     "note": "The knight on d5 is pinned by the rook: moving it would expose the king on d8. White can capture it with the c-pawn."
    }
   ]
  }
 },
 {
  "id": "cb_skewer",
  "cat": "combo",
  "title": "スキュア(串刺し)",
  "fen": "4q3/8/8/4k3/8/8/8/R5K1 w - - 0 1",
  "intro": "ピンの逆。前の価値ある駒(キング)にチェックをかけ、それが逃げた後ろにいる駒を頂く技。串に刺すように一直線に並んだ二枚を刈り取ります。",
  "takeaway": "キングと大駒が同じ縦・横・斜めに並んでいたら、チェックでキングをどかして背後の駒を取れないか探す。",
  "moves": [
   {
    "san": "Re1+",
    "note": "ルークが縦のチェック。キングとその真後ろのクイーンが一直線に『串刺し』になっている。"
   },
   {
    "san": "Kd5",
    "note": "ここではキングをd5へ逃がす変化を見る。チェックへの対応には他のキング移動もある。"
   },
   {
    "san": "Rxe8",
    "note": "背後にいたクイーンを頂く。これが串刺しの狙い。"
   }
  ],
  "en": {
   "title": "Skewer",
   "intro": "A skewer is often described as the reverse of a pin: check the more valuable front piece, then take the piece behind it after the king moves.",
   "takeaway": "When a king and a valuable piece line up, look for a checking move that forces the king away and exposes the rear target.",
   "moves": [
    {
     "san": "Re1+",
     "note": "The rook checks along the e-file. The king and queen are lined up behind one another."
    },
    {
     "san": "Kd5",
     "note": "The king moves aside; this line uses Kd5."
    },
    {
     "san": "Rxe8",
     "note": "The rook captures the queen behind the king. That is the point of a skewer."
    }
   ]
  }
 },
 {
  "id": "cb_backrank",
  "cat": "combo",
  "title": "バックランク・メイト(最終段の詰み)",
  "fen": "6k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1",
  "intro": "自分のポーンで守られたキングは安全に見えますが、そのポーンが逃げ道をふさいでいると、キング側のバックランク(最終段)にルークやクイーンが飛び込んで詰むことがあります。",
  "takeaway": "キングの前のポーンが動いていないと、バックランクは詰みの危険地帯。自分のキングにも『逃げ道の穴(ルフト)』を作っておく。",
  "moves": [
   {
    "san": "Rd8#",
    "note": "ルークが黒のバックランクに侵入してチェックメイト。キングはf7・g7・h7の自分のポーンに塞がれ、逃げ場がない。"
   }
  ],
  "en": {
   "title": "Back-Rank Mate",
   "intro": "A king can look safe behind its own pawns, but those pawns can also remove every escape square. A rook or queen invading the back rank can then deliver mate.",
   "takeaway": "Watch for a king whose pawn shield has not made an escape square. Give your own king luft before the back rank becomes a trap.",
   "moves": [
    {
     "san": "Rd8#",
     "note": "The rook invades Black's back rank and checkmates. The pawns on f7, g7, and h7 leave the king no escape."
    }
   ]
  }
 },
 {
  "id": "cb_double",
  "cat": "combo",
  "title": "ダブルアタック(クイーンの二重攻撃)",
  "fen": "4k3/8/8/8/7b/8/8/Q5K1 w - - 0 1",
  "intro": "クイーンは縦・横・斜めに動けるので、一手で二つの離れた的を同時に攻められます。チェックをかけながら別の駒も狙えば、確実に駒得できます。",
  "takeaway": "クイーンを動かすときは『この一手で二つ以上のものを攻められないか?』と常に考える。チェックつきの二重攻撃は特に強力。",
  "moves": [
   {
    "san": "Qa4+",
    "note": "斜めにチェックをかけつつ、同じクイーンが横のラインでh4のビショップも攻めている二重攻撃。"
   },
   {
    "san": "Kf8",
    "note": "チェックを受けてキングが逃げる。ビショップは守れない。"
   },
   {
    "san": "Qxh4",
    "note": "ビショップを頂く。ここではチェックではないが、二重攻撃で得をする典型。"
   }
  ],
  "en": {
   "title": "Double Attack (Queen)",
   "intro": "Because the queen moves along ranks, files, and diagonals, it can attack two distant targets in one move. A double attack with check is especially forcing.",
   "takeaway": "Before moving the queen, ask whether it can attack two or more targets. A checking double attack deserves particular attention.",
   "moves": [
    {
     "san": "Qa4+",
     "note": "The queen gives diagonal check and also attacks the bishop on h4 along the rank."
    },
    {
     "san": "Kf8",
     "note": "The king moves to f8; in this line the bishop is left undefended."
    },
    {
     "san": "Qxh4",
     "note": "The queen takes the bishop. It is not check here, but the double attack has won material."
    }
   ]
  }
 },
 {
  "id": "eg_rook",
  "cat": "endgame",
  "title": "ルークでのメイト(基本形)",
  "fen": "4k3/8/4K3/8/8/8/8/R7 w - - 0 1",
  "intro": "キングとルークだけで相手のキングを詰ませる、最も基本的で必ず覚えるべき寄せ。カギは自分のキングで相手のキングの逃げ道を奪う『オポジション(向かい合い)』です。",
  "takeaway": "ルーク単独では詰まない。自分のキングを相手のキングの正面に置いて逃げ道を消し、ルークで最後の一線を封じる。",
  "moves": [
   {
    "san": "Ra8#",
    "note": "自分のキングがe6から相手のキングのd7・e7・f7の逃げ道をすべて塞いでいるので、ルークが最終列に回り込んでチェックメイト。キングとルークの連携が要。"
   }
  ],
  "en": {
   "title": "Rook Checkmate: The Basic Position",
   "intro": "Checkmating with king and rook is a fundamental endgame skill. The key is to use your king to take away the enemy king's escape squares, often with opposition.",
   "takeaway": "A rook cannot mate by itself. Bring your king in front of the enemy king, remove the escape squares, and use the rook to close the final rank.",
   "moves": [
    {
     "san": "Ra8#",
     "note": "The white king on e6 controls d7, e7, and f7, so the rook can deliver mate from the back rank. King and rook must work together."
    }
   ]
  }
 },
 {
  "id": "eg_tworooks",
  "cat": "endgame",
  "title": "ラダーメイト(二枚のルークの階段)",
  "fen": "4k3/R7/1R6/8/8/8/8/6K1 w - - 0 1",
  "intro": "ルークが二枚あれば自分のキングの助けは不要。片方で相手のキングの逃げる段を封じ、もう片方でチェックをかける『階段(ラダー)』で、端まで追い詰めて詰ませます。",
  "takeaway": "二枚のルークは『一枚が逃げ道の段を封鎖、もう一枚がチェック』を交互に繰り返して、相手のキングを盤の端へ追い詰める。",
  "moves": [
   {
    "san": "Rb8#",
    "note": "a7のルークが7段目(キングの逃げ道 d7・e7・f7)を完全に封鎖しているので、b6のルークが8段目にチェックメイト。これが階段メイトの決め。"
   }
  ],
  "en": {
   "title": "Ladder Mate with Two Rooks",
   "intro": "Two rooks can normally checkmate without the king's help by taking away one rank at a time and alternating checks. This is the ladder, or staircase, technique.",
   "takeaway": "Use one rook to seal an escape rank and the other to give check. Repeat the pattern until the enemy king reaches the edge.",
   "moves": [
    {
     "san": "Rb8#",
     "note": "The rook on a7 seals the seventh rank, including d7, e7, and f7. The rook on b6 checks from the eighth rank for the ladder mate."
    }
   ]
  }
 },
 {
  "id": "eg_queen",
  "cat": "endgame",
  "title": "クイーンでのメイト(基本形)",
  "fen": "6k1/2Q5/6K1/8/8/8/8/8 w - - 0 1",
  "intro": "クイーンは強力なので、キングの助けがあればすぐ詰みます。ただしクイーン単独でキングに隣接すると、味方のキングが支えていない限り取られてしまう点に注意。",
  "takeaway": "クイーンでキングに隣接して詰ませるときは、必ず自分のキングでそのクイーンを『守れる』位置に置いておく。ステイルメイト(手詰まりの引き分け)にも注意。",
  "moves": [
   {
    "san": "Qg7#",
    "note": "クイーンがキングの隣に飛び込んでチェックメイト。g6の自分のキングがg7を守っているので、相手のキングはクイーンを取れず、逃げ道もない。"
   }
  ],
  "en": {
   "title": "Queen Checkmate: The Basic Position",
   "intro": "The queen is powerful, but a queen next to the enemy king must be protected by your king or another piece, or it may simply be captured.",
   "takeaway": "When placing the queen next to the king, make sure your king protects it. Also watch for stalemate when removing escape squares.",
   "moves": [
    {
     "san": "Qg7#",
     "note": "The queen moves next to the king and gives mate. The king on g6 protects g7, so the black king cannot capture the queen."
    }
   ]
  }
 },
 {
  "id": "eg_promote",
  "cat": "endgame",
  "title": "パスポーンを昇格させる",
  "fen": "8/1P4k1/8/8/8/8/8/6K1 w - - 0 1",
  "intro": "相手のポーンに邪魔されない『パスポーン(通過ポーン)』は、最終列まで進めばクイーンなどに昇格できます。相手のキングが遠ければ、そのまま押し込んで大逆転の駒得です。",
  "takeaway": "終盤で最も価値があるのは『昇格できるポーン』。相手のキングがそのポーンを止められる範囲(四角形)の外にいるうちに、一気に押し進める。",
  "moves": [
   {
    "san": "b8=Q",
    "note": "ポーンが最終列に到達し、クイーンに昇格。相手のキング(g7)は遠すぎて止められなかった。ここからはクイーンとキングで詰ませにいく。"
   }
  ],
  "en": {
   "title": "Promoting a Passed Pawn",
   "intro": "A passed pawn with no opposing pawn in front of it can promote on the last rank. If the enemy king is too far away, the pawn can become a decisive new piece.",
   "takeaway": "In the endgame, a pawn that can promote is extremely valuable. Use the rule of the square to see whether the king can catch it.",
   "moves": [
    {
     "san": "b8=Q",
     "note": "The pawn reaches the last rank and promotes to a queen. The king on g7 is too far away to stop it; the queen and king can now finish the game."
    }
   ]
  }
 },
 {
  "id": "op_scotch",
  "cat": "opening",
  "title": "スコッチ・ゲーム",
  "fen": null,
  "intro": "3手目でいきなり中央をぶつけて開く、はっきりした戦い方。難しい駆け引きより『中央を開いて素早く駒を働かせる』を体感できる、初心者に優しい攻めの定跡です。",
  "takeaway": "早い d4 で中央を開き、駒の通り道を作る。相手のビショップに当てて手を稼ぎつつ、テンポよく展開する。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e5",
    "note": "対称に応じる。"
   },
   {
    "san": "Nf3",
    "note": "e5に当てて展開。"
   },
   {
    "san": "Nc6",
    "note": "ポーンを守りつつ展開。"
   },
   {
    "san": "d4",
    "note": "スコッチ。すぐに中央を開いて主導権を取りにいく。"
   },
   {
    "san": "exd4",
    "note": "取らせて中央を清算。"
   },
   {
    "san": "Nxd4",
    "note": "ナイトで取り返し、中央の好位置に据える。"
   },
   {
    "san": "Bc5",
    "note": "d4のナイトに当てて手得をねらう鋭い一手。"
   },
   {
    "san": "Nb3",
    "note": "ナイトを下げてビショップに当て返す。"
   },
   {
    "san": "Bb6",
    "note": "ビショップはにらみを保ったまま静かに退く。両者、駒が気持ちよく働く形。"
   }
  ],
  "en": {
   "title": "Scotch Game",
   "intro": "White challenges the center immediately on move three. It is a clear, active opening for experiencing open lines and quick development.",
   "takeaway": "Play d4 early to open lines. When a bishop attacks your knight, use the tempo to reposition and keep developing.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes central space."
    },
    {
     "san": "e5",
     "note": "Black answers symmetrically."
    },
    {
     "san": "Nf3",
     "note": "The knight attacks e5 while developing."
    },
    {
     "san": "Nc6",
     "note": "The knight protects the pawn and develops."
    },
    {
     "san": "d4",
     "note": "White opens the center at once and fights for the initiative."
    },
    {
     "san": "exd4",
     "note": "Black exchanges in the center."
    },
    {
     "san": "Nxd4",
     "note": "White recaptures with the knight and establishes it in the center."
    },
    {
     "san": "Bc5",
     "note": "The bishop attacks the knight and gains a tempo."
    },
    {
     "san": "Nb3",
     "note": "The knight retreats while attacking the bishop in return."
    },
    {
     "san": "Bb6",
     "note": "The bishop keeps its diagonal and retreats calmly; both sides have active pieces."
    }
   ]
  }
 },
 {
  "id": "op_scandinavian",
  "cat": "opening",
  "title": "スカンジナビアン・ディフェンス",
  "fen": null,
  "intro": "黒が2手目でいきなり中央のポーンをぶつけて交換してしまう、分かりやすい受け方。早くにクイーンが出てくるので、『クイーンを早く動かしすぎない』という原則を逆に学べます。",
  "takeaway": "早すぎるクイーンの出撃は相手に手を稼がれる。黒はそれを承知で、駒得を避けつつ手堅く駒を組む。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "d5",
    "note": "スカンジナビアン。中央のポーンをすぐにぶつける。"
   },
   {
    "san": "exd5",
    "note": "取っておく。"
   },
   {
    "san": "Qxd5",
    "note": "クイーンで取り返す。ただし早すぎる出撃は狙われやすい。"
   },
   {
    "san": "Nc3",
    "note": "ナイトを展開しながらクイーンに当て、手を稼ぐ。"
   },
   {
    "san": "Qa5",
    "note": "当たりを避けつつ、にらみの利く安全なマスへ。"
   },
   {
    "san": "d4",
    "note": "中央を確保して展開を広げる。"
   },
   {
    "san": "Nf6",
    "note": "ナイトを出して反撃の芽を作る。"
   },
   {
    "san": "Nf3",
    "note": "自然に展開。"
   },
   {
    "san": "c6",
    "note": "クイーンの退路とキングの安全を用意する堅実な一手。"
   }
  ],
  "en": {
   "title": "Scandinavian Defense",
   "intro": "Black challenges and exchanges the central pawn immediately on move two. The early queen move is a useful way to learn why moving the queen too often can cost tempi.",
   "takeaway": "An early queen sortie can let the opponent gain tempi. Black accepts that trade-off for a clear, solid structure.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes central space."
    },
    {
     "san": "d5",
     "note": "The Scandinavian: Black immediately challenges the e-pawn."
    },
    {
     "san": "exd5",
     "note": "White captures in the center."
    },
    {
     "san": "Qxd5",
     "note": "Black recaptures with the queen, accepting that the early queen may be chased."
    },
    {
     "san": "Nc3",
     "note": "The knight develops with tempo against the queen."
    },
    {
     "san": "Qa5",
     "note": "The queen steps away to a useful square."
    },
    {
     "san": "d4",
     "note": "White builds a broad center and develops."
    },
    {
     "san": "Nf6",
     "note": "Black develops a knight and prepares counterplay."
    },
    {
     "san": "Nf3",
     "note": "White develops naturally."
    },
    {
     "san": "c6",
     "note": "...c6 gives the queen useful squares and supports a solid setup."
    }
   ]
  }
 },
 {
  "id": "op_kingsindian",
  "cat": "opening",
  "title": "キングス・インディアン・ディフェンス",
  "fen": null,
  "intro": "黒がいったん中央を相手に譲り、g7のビショップ(フィアンケット)と後の e5・f5 で反撃をねらう、人気の高い戦い方。『すぐ中央で張り合わない』柔らかい発想を学べます。",
  "takeaway": "中央を一時的に譲っても、あとから e5・f5 で反撃できる。キングを早く囲い、狙いを持って反撃の一手を用意する。",
  "moves": [
   {
    "san": "d4",
    "note": "クイーン側のポーンで中央を取る。"
   },
   {
    "san": "Nf6",
    "note": "中央のe4進出をけん制。"
   },
   {
    "san": "c4",
    "note": "もう一歩広げ、大きな中央をめざす。"
   },
   {
    "san": "g6",
    "note": "ビショップを g7 に構える(フィアンケット)準備。"
   },
   {
    "san": "Nc3",
    "note": "展開しながら中央を支える。"
   },
   {
    "san": "Bg7",
    "note": "長い斜めから中央をにらむキングス・インディアンの主役。"
   },
   {
    "san": "e4",
    "note": "白は堂々と中央を占領する。"
   },
   {
    "san": "d6",
    "note": "e5の反撃に備え、中央を静かに支える。"
   },
   {
    "san": "Nf3",
    "note": "自然に展開。"
   },
   {
    "san": "O-O",
    "note": "黒はまずキングを安全に。反撃はそのあと。"
   },
   {
    "san": "Be2",
    "note": "白も展開してキャスリングを準備。"
   },
   {
    "san": "e5",
    "note": "満を持しての中央への反撃。ここから激しい戦いになる。"
   }
  ],
  "en": {
   "title": "King's Indian Defense",
   "intro": "Black allows White a broad center, then plans counterplay with the fianchettoed bishop and ...e5 or ...f5. It teaches a flexible approach instead of fighting for every central square immediately.",
   "takeaway": "A temporary concession of the center can be acceptable if you have a concrete counterstrike. Castle early and prepare the break with purpose.",
   "moves": [
    {
     "san": "d4",
     "note": "White claims central space with the queen's pawn."
    },
    {
     "san": "Nf6",
     "note": "The knight controls e4 and develops."
    },
    {
     "san": "c4",
     "note": "White expands with c4."
    },
    {
     "san": "g6",
     "note": "Black prepares the bishop's fianchetto on g7."
    },
    {
     "san": "Nc3",
     "note": "White supports the center while developing."
    },
    {
     "san": "Bg7",
     "note": "The bishop takes the long diagonal, the signature piece of the King's Indian."
    },
    {
     "san": "e4",
     "note": "White occupies the center confidently."
    },
    {
     "san": "d6",
     "note": "Black supports the center and prepares ...e5."
    },
    {
     "san": "Nf3",
     "note": "White develops naturally."
    },
    {
     "san": "O-O",
     "note": "Black castles before launching the counterplay."
    },
    {
     "san": "Be2",
     "note": "White develops and prepares to castle."
    },
    {
     "san": "e5",
     "note": "Black finally strikes in the center with ...e5."
    }
   ]
  }
 },
 {
  "id": "op_english",
  "cat": "opening",
  "title": "イングリッシュ・オープニング",
  "fen": null,
  "intro": "1.c4 と、e4/d4 以外から始めるおおらかな戦い方。相手のシチリアンを『白番で・一手多く』指すような形になり、じっくり駒を組む楽しさがあります。",
  "takeaway": "最初の一手は e4/d4 だけではない。c4 で横から中央に圧力をかけ、フィアンケットでゆっくり good な形を作る。",
  "moves": [
   {
    "san": "c4",
    "note": "横から中央のd5・e4に圧力をかけるイングリッシュ。"
   },
   {
    "san": "e5",
    "note": "黒は中央を取り返しにいく(逆シチリアンの形)。"
   },
   {
    "san": "Nc3",
    "note": "展開しつつ d5 をにらむ。"
   },
   {
    "san": "Nf6",
    "note": "対称に展開。"
   },
   {
    "san": "Nf3",
    "note": "e5に当てて自然に展開。"
   },
   {
    "san": "Nc6",
    "note": "ポーンを守る。"
   },
   {
    "san": "g3",
    "note": "ビショップを g2 へ構える準備。長い斜めが主役になる。"
   },
   {
    "san": "d5",
    "note": "黒は中央を広げて反撃。"
   },
   {
    "san": "cxd5",
    "note": "いったん取っておく。"
   },
   {
    "san": "Nxd5",
    "note": "ナイトで取り返し、中央の好位置に。両者、原則通りの好形。"
   }
  ],
  "en": {
   "title": "English Opening",
   "intro": "The English begins with 1.c4 instead of the immediate e4 or d4. The position can resemble a reversed Sicilian, with White having an extra tempo to build patiently.",
   "takeaway": "The first move need not be e4 or d4. Use c4 to pressure the center from the side and build a good position with a fianchetto.",
   "moves": [
    {
     "san": "c4",
     "note": "The English pressures d5 and e4 from the side."
    },
    {
     "san": "e5",
     "note": "Black occupies the center, creating a reversed-Sicilian structure."
    },
    {
     "san": "Nc3",
     "note": "The knight develops and eyes d5."
    },
    {
     "san": "Nf6",
     "note": "Black develops symmetrically."
    },
    {
     "san": "Nf3",
     "note": "White develops while putting pressure on e5."
    },
    {
     "san": "Nc6",
     "note": "The knight supports the pawn."
    },
    {
     "san": "g3",
     "note": "White prepares the bishop's fianchetto; the long diagonal will matter."
    },
    {
     "san": "d5",
     "note": "Black expands and counterattacks in the center."
    },
    {
     "san": "cxd5",
     "note": "White captures once in the center."
    },
    {
     "san": "Nxd5",
     "note": "Black recaptures with the knight. Both sides have developed according to sound principles."
    }
   ]
  }
 },
 {
  "id": "cb_smother",
  "cat": "combo",
  "title": "スマザー・メイト(窒息の詰み)",
  "fen": "5r1k/pp4pp/8/4N3/8/1Q6/PP4PP/6K1 w - - 0 1",
  "intro": "自分の駒に囲まれて逃げ道のないキングを、ナイト一枚で仕留める華麗な決め技。クイーンをあえて捨てて相手のルークを呼び込み、ナイトの一撃で詰ます有名な手順です。",
  "takeaway": "逃げ道が味方でふさがれたキングはナイトに弱い。ダブルチェックでキングを隅へ追い込み、クイーンを捨ててでも詰みの形を作る。",
  "moves": [
   {
    "san": "Nf7+",
    "note": "ナイトが飛び込んでチェック。ここではキングをg8へ逃がす変化を見る。ルークでナイトを取る応手もある。"
   },
   {
    "san": "Kg8",
    "note": "隅を避けて g8 へ。"
   },
   {
    "san": "Nh6+",
    "note": "ナイトが跳ねると、後ろのクイーンがb3-g8の斜めで同時にチェック(ダブルチェック=ダブルチェック)。ダブルチェックはキングが動くしかない。"
   },
   {
    "san": "Kh8",
    "note": "g8はふさがれ、キングは隅の h8 へ押し戻される。"
   },
   {
    "san": "Qg8+",
    "note": "クイーンを大胆に捨てる!h6のナイトが g8 を支えているのでキングでは取れない。"
   },
   {
    "san": "Rxg8",
    "note": "しかたなくルークで取る。これでキングの逃げ道(g8)が自分のルークでふさがれた。"
   },
   {
    "san": "Nf7#",
    "note": "ナイトが戻ってスマザー・メイト。キングは味方の駒に囲まれて動けず、ナイトも取れない完全な詰み。"
   }
  ],
  "en": {
   "title": "Smothered Mate",
   "intro": "A king surrounded by its own pieces can be finished by a knight. This famous pattern sacrifices the queen to force the defending rook into the square needed for the final knight move.",
   "takeaway": "A king boxed in by its own pieces is vulnerable to a knight. Sometimes a queen sacrifice is justified if it creates a forced smothered mate.",
   "moves": [
    {
     "san": "Nf7+",
     "note": "The knight checks. The king cannot return to h8 and moves to g8 in this line."
    },
    {
     "san": "Kg8",
     "note": "The king steps away from the corner to g8."
    },
    {
     "san": "Nh6+",
     "note": "The knight moves and the queen's discovered line to g8 also checks. In a double check, the king must move."
    },
    {
     "san": "Kh8",
     "note": "The g8 escape is covered, so the king is pushed back to h8."
    },
    {
     "san": "Qg8+",
     "note": "The queen offers itself on g8. The knight on h6 protects that square, so the king cannot take it."
    },
    {
     "san": "Rxg8",
     "note": "The rook captures the queen, filling the last escape square with its own piece."
    },
    {
     "san": "Nf7#",
     "note": "The knight returns for smothered mate: the king is boxed in and cannot capture the knight."
    }
   ]
  }
 },
 {
  "id": "cb_discovered",
  "cat": "combo",
  "title": "ディスカバード・アタック(発見攻撃)",
  "fen": "3qk2r/ppp2ppp/8/4N3/8/8/PPP2PPP/4R1K1 w - - 0 1",
  "intro": "手前の駒をどけると、後ろに隠れていた駒の利きが『発見』されて相手を襲う戦術。特にチェックをかけながら別の駒を襲えば、相手はチェックを避けるしかなく、狙った駒をタダで頂けます。",
  "takeaway": "自分の駒が『別の駒の利きをさえぎっていないか』を見る。どければチェックになる駒があれば、その一手で二つの標的を同時に攻められる。",
  "moves": [
   {
    "san": "Nc6+",
    "note": "ナイトを跳ねると、後ろに隠れていたルークがe筋でチェック(ディスカバードチェック)。しかもナイトはd8のクイーンもにらんでいる。"
   },
   {
    "san": "Kf8",
    "note": "チェックを避けてキングが逃げる。この『よける一手』のあいだに、ねらった駒は取り放題。"
   },
   {
    "san": "Nxd8",
    "note": "タダでクイーンを頂く。キングが f8 にいてルークも h8 から動けず、取り返せない。発見攻撃の狙いが決まった。"
   }
  ],
  "en": {
   "title": "Discovered Attack",
   "intro": "When a front piece moves, it can reveal the line of a piece behind it. If the discovered line gives check while the moving piece attacks something else, the defender may lose the second target.",
   "takeaway": "Look for a piece blocking a rook, bishop, or queen. Moving it may reveal check and create a second attack at the same time.",
   "moves": [
    {
     "san": "Nc6+",
     "note": "The knight moves, revealing the rook's check along the e-file. The knight also attacks the queen on d8."
    },
    {
     "san": "Kf8",
     "note": "The king moves to f8 to answer the check, leaving the queen under attack."
    },
    {
     "san": "Nxd8",
     "note": "The knight takes the queen. With the king on f8, the rook on h8 cannot recapture; the discovered attack has worked."
    }
   ]
  }
 },
 {
  "id": "eg_opposition",
  "cat": "endgame",
  "title": "オポジションでポーンを昇格させる",
  "fen": "4k3/8/4K3/4P3/8/8/8/8 w - - 0 1",
  "intro": "ポーン1個の終盤は、キングの使い方がすべて。ポーンより前にキングを進め、『オポジション(キングが1マス空けて正面で向かい合う)』で相手のキングを押し下げれば、ポーンを安全に昇格させられます。",
  "takeaway": "ポーンだけでは前に進めない。まずキングを先行させて相手のキングを押しやり、キングがポーンを守りながら一歩ずつ最終列へ運ぶ。",
  "moves": [
   {
    "san": "Kd6",
    "note": "ポーンの前にキングを先行させ、相手のキングを押し下げる。これが昇格の第一歩。"
   },
   {
    "san": "Kd8",
    "note": "黒のキングは下がるしかない。"
   },
   {
    "san": "e6",
    "note": "キングに守られながらポーンを一歩進める。"
   },
   {
    "san": "Ke8",
    "note": "黒は正面で粘る。"
   },
   {
    "san": "e7",
    "note": "さらに前進。キングが守っているので取られない。黒はどくしかない。"
   },
   {
    "san": "Kf7",
    "note": "e7のポーンには触れられず、キングは横へ。"
   },
   {
    "san": "Kd7",
    "note": "キングが昇格マス(e8)の隣に回り込み、道を空ける。"
   },
   {
    "san": "Kf6",
    "note": "黒はもう止められない。"
   },
   {
    "san": "e8=Q",
    "note": "ポーンがクイーンに昇格!キングのエスコートで通過ポーンを女王に変えた。"
   }
  ],
  "en": {
   "title": "Promotion with Opposition",
   "intro": "In a king-and-pawn ending, king placement is everything. Put your king in front of the pawn and use opposition to push the enemy king away.",
   "takeaway": "A pawn cannot promote safely by itself. Lead with the king, drive the opposing king back, and escort the pawn toward promotion.",
   "moves": [
    {
     "san": "Kd6",
     "note": "The king moves ahead of the pawn and begins to push the enemy king back."
    },
    {
     "san": "Kd8",
     "note": "The black king retreats."
    },
    {
     "san": "e6",
     "note": "The pawn advances while protected by the king."
    },
    {
     "san": "Ke8",
     "note": "Black holds the opposition from the front."
    },
    {
     "san": "e7",
     "note": "The pawn advances again; the king protects it, so Black must give way."
    },
    {
     "san": "Kf7",
     "note": "The black king steps aside because it cannot capture the protected pawn."
    },
    {
     "san": "Kd7",
     "note": "The white king approaches the promotion square and clears the path."
    },
    {
     "san": "Kf6",
     "note": "Black is too late to stop the pawn."
    },
    {
     "san": "e8=Q",
     "note": "The pawn promotes under the king's escort."
    }
   ]
  }
 },
 {
  "id": "cb_doublecheck",
  "cat": "combo",
  "title": "ダブルチェック(両王手)",
  "fen": "2k3r1/pp6/2N5/8/8/8/8/2R4K w - - 0 1",
  "intro": "二枚の駒で同時にチェックをかける『ダブルチェック』。合い駒もできず、チェックしている駒を取ることもできない——キングはただ動くしかありません。守り駒がいくら多くても関係ない、最強のチェックです。",
  "takeaway": "ダブルチェックは『キングが動く』以外に受けがない。駒を跳ねて味方の大駒の利きを開けば、相手の守りを無視してキングを追い立てられる。",
  "moves": [
   {
    "san": "Ne7+",
    "note": "ナイトが跳ねてチェック。同時に、後ろに隠れていたルークもc筋でチェック(ダブルチェック)。二つ同時のチェックは取っても防げない。"
   },
   {
    "san": "Kb8",
    "note": "ダブルチェックなので合い駒や一方の駒取りでは解決できず、キングをb8へ逃がす。"
   },
   {
    "san": "Nxg8",
    "note": "チェックをかけていたナイトが、そのまま無防備なルークを頂く。ダブルチェックで相手の守りを丸ごと無視できた。"
   }
  ],
  "en": {
   "title": "Double Check",
   "intro": "A double check occurs when two pieces check at once. Blocking one line or capturing one checker is not enough; the king must move.",
   "takeaway": "When a knight move opens a rook or bishop line, check whether the move also checks with the knight. Double check can force the king away from a valuable piece.",
   "moves": [
    {
     "san": "Ne7+",
     "note": "The knight checks and opens the rook's c-file check at the same time. That is a double check."
    },
    {
     "san": "Kb8",
     "note": "The king must move; blocking or capturing one checker cannot solve both checks."
    },
    {
     "san": "Nxg8",
     "note": "The knight captures the exposed rook. The double check gave it time to do so."
    }
   ]
  }
 },
 {
  "id": "cb_epaulette",
  "cat": "combo",
  "title": "エポーレット・メイト(肩章の詰み)",
  "fen": "3rkr2/8/8/8/8/8/Q7/6K1 w - - 0 1",
  "intro": "キングの両どなりを自分のルーク(=肩章)がふさいでいると、正面から一枚の駒でチェックするだけで詰みます。味方の駒が逃げ道をふさいでいる『自分でハマった』形をとがめる決め技です。",
  "takeaway": "相手のキングの逃げ道を『相手自身の駒』がふさいでいないかを見る。両脇が埋まっていれば、正面からの一撃で詰む。",
  "moves": [
   {
    "san": "Qe6#",
    "note": "クイーンが正面からチェック。キングの両脇は自分のルークでふさがれ、斜め前の逃げ道もクイーンが全部消しているのでチェックメイト。"
   }
  ],
  "en": {
   "title": "Epaulette Mate",
   "intro": "When a king's own rooks occupy both neighboring squares, a queen can sometimes mate from the front. The king's own pieces become its prison.",
   "takeaway": "Look for escape squares blocked by the opponent's own pieces. If both sides are sealed, a frontal check may be decisive.",
   "moves": [
    {
     "san": "Qe6#",
     "note": "The queen checks from the front. The rooks block both sides, while the queen covers the diagonal and forward escapes."
    }
   ]
  }
 },
 {
  "id": "cb_anastasia",
  "cat": "combo",
  "title": "アナスタシアン・メイト",
  "fen": "8/4N1pk/8/8/R7/8/8/6K1 w - - 0 1",
  "intro": "ナイトとルークが息を合わせる、端のキングを仕留める有名な詰み形。ナイトがキングの脱出口をふさぎ、ルークが横から一気にチェックして逃げ道を断ちます。",
  "takeaway": "ナイトが e7 から g8・g6 の逃げ道をふさいでいるのがカギ。端に寄ったキングは、ルークを横から回すだけで詰む。",
  "moves": [
   {
    "san": "Rh4#",
    "note": "ルークが h筋に回り込んでチェック。ナイトが g6・g8 をふさぎ、ルークが h筋の上下を封じているのでチェックメイト。"
   }
  ],
  "en": {
   "title": "Anastasia's Mate",
   "intro": "A rook and knight coordinate to mate a king near the edge. The knight covers the escape squares while the rook checks from the side.",
   "takeaway": "The knight on e7 controls g8 and g6. Once the king is on the edge, bring the rook across the h-file.",
   "moves": [
    {
     "san": "Rh4#",
     "note": "The rook reaches the h-file and checks. The knight covers g6 and g8, while the rook controls the h-file escapes."
    }
   ]
  }
 },
 {
  "id": "eg_breakthrough",
  "cat": "endgame",
  "title": "ブレイクスルー(ポーンの突破)",
  "fen": "6k1/ppp5/8/PPP5/8/8/8/6K1 w - - 0 1",
  "intro": "3対3で向かい合ったポーンでも、正しい順番で突けば一枚だけ通過ポーンを作って昇格できることがあります。数が同じでも『突破口』を作る、終盤の代表的な手筋です。",
  "takeaway": "真ん中から突くのがコツ。この例では黒がc7で取る変化を見ます。相手の取り方に応じて、残ったポーンを走らせる順番を考える。",
  "moves": [
   {
    "san": "b6",
    "note": "真ん中のポーンを突き捨てる。a7とc7の両方に取られる位置なので、相手の応手を見て突破の順番を選ぶ。"
   },
   {
    "san": "cxb6",
    "note": "この教材ではc7で取る変化を進める。a7で取る場合は別の順番になる。"
   },
   {
    "san": "a6",
    "note": "今度は逆側から突き捨てる。b7がねらわれる。"
   },
   {
    "san": "bxa6",
    "note": "ここではb7で取り返す変化を進める。これでc筋ががら空きになった。"
   },
   {
    "san": "c6",
    "note": "残った c ポーンが誰にも止められない通過ポーンに。相手のキングは遠すぎる。"
   },
   {
    "san": "Kf7",
    "note": "キングが追いかけるが…"
   },
   {
    "san": "c7",
    "note": "止まらない。"
   },
   {
    "san": "Ke7",
    "note": "間に合わない。"
   },
   {
    "san": "c8=Q",
    "note": "昇格!同じ3枚同士から、突き捨ての妙で女王が生まれた。"
   }
  ],
  "en": {
   "title": "Pawn Breakthrough",
   "intro": "Even three pawns against three can create a passed pawn if they advance in the right order. The goal is to open a breakthrough rather than to win every exchange immediately.",
   "takeaway": "Start with the central pawn, but calculate the opponent's choice. This line follows ...cxb6; ...axb6 requires a different order.",
   "moves": [
    {
     "san": "b6",
     "note": "The central pawn offers itself. Both a7 and c7 can capture, so the breakthrough order depends on Black's reply."
    },
    {
     "san": "cxb6",
     "note": "This line follows ...cxb6. If ...axb6 is played, the continuation changes."
    },
    {
     "san": "a6",
     "note": "The other wing pawn advances and attacks b7."
    },
    {
     "san": "bxa6",
     "note": "Here Black recaptures with b7, opening the c-file for the last pawn."
    },
    {
     "san": "c6",
     "note": "The remaining c-pawn becomes a passed pawn. The king is too far away in this line."
    },
    {
     "san": "Kf7",
     "note": "The king chases the pawn, but it is already too late."
    },
    {
     "san": "c7",
     "note": "The pawn keeps running."
    },
    {
     "san": "Ke7",
     "note": "The king cannot catch it."
    },
    {
     "san": "c8=Q",
     "note": "The pawn promotes. The breakthrough created a queen from an equal pawn mass."
    }
   ]
  }
 },
 {
  "id": "eg_square",
  "cat": "endgame",
  "title": "スクエアルール(四角形の法則)",
  "fen": "8/8/8/5k2/P7/8/8/7K w - - 0 1",
  "intro": "通過ポーンを相手のキングが止められるかは、頭の中に『四角形』を描けば一目で分かります。ポーンの昇格マスを角にした正方形の中に相手のキングがいれば追いつける、外なら昇格、という便利な法則です。",
  "takeaway": "ポーンと昇格マスを一辺とする正方形を思い浮かべる。相手のキングがその四角の外にいれば、まっすぐ走らせるだけで昇格できる。",
  "moves": [
   {
    "san": "a5",
    "note": "ポーンを走らせる。黒のキングは四角形の外にいるので追いつけない。"
   },
   {
    "san": "Ke6",
    "note": "キングは懸命に戻ろうとするが…"
   },
   {
    "san": "a6",
    "note": "かまわず前進。"
   },
   {
    "san": "Kd6",
    "note": "一歩ずつ追うが間に合わない。"
   },
   {
    "san": "a7",
    "note": "あと一歩。"
   },
   {
    "san": "Kc7",
    "note": "キングがようやく近づいたが…"
   },
   {
    "san": "a8=Q",
    "note": "先に昇格!『四角形の外なら追いつけない』を目で確かめられた。"
   }
  ],
  "en": {
   "title": "The Rule of the Square",
   "intro": "You can often tell whether a king can catch a passed pawn by imagining a square from the pawn to its promotion rank. A king inside the square can catch it; a king outside cannot, assuming no other tactics intervene.",
   "takeaway": "Visualize the pawn's square. If the opposing king is outside it, the pawn may promote by running straight ahead.",
   "moves": [
    {
     "san": "a5",
     "note": "The pawn advances. The black king is outside the square and cannot catch it."
    },
    {
     "san": "Ke6",
     "note": "The king tries to approach."
    },
    {
     "san": "a6",
     "note": "The pawn continues forward."
    },
    {
     "san": "Kd6",
     "note": "The king follows, but is still too slow."
    },
    {
     "san": "a7",
     "note": "One step from promotion."
    },
    {
     "san": "Kc7",
     "note": "The king finally approaches, but not in time."
    },
    {
     "san": "a8=Q",
     "note": "The pawn promotes first: outside the square means no catch."
    }
   ]
  }
 },
 {
  "id": "op_kingsgambit",
  "cat": "opening",
  "title": "キングス・ギャンビット",
  "fen": null,
  "intro": "2手目でポーンを1つ差し出して中央を開き、一気に攻めをめざす古き良き積極策。ここでは無理に取らずに受ける『拒否形』で、落ち着いた駒組みを学びます。",
  "takeaway": "ポーンを差し出されても、必ず取る必要はない。中央とビショップの働きを優先し、堅く組んで受け止める手もある。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e5",
    "note": "対称に応じる。"
   },
   {
    "san": "f4",
    "note": "キングス・ギャンビット。ポーンを差し出して中央を開き、攻めをめざす。"
   },
   {
    "san": "Bc5",
    "note": "取らずに受ける拒否形。f2の弱点をにらむ好位置にビショップを出す。"
   },
   {
    "san": "Nf3",
    "note": "自然に展開し、e5もにらむ。"
   },
   {
    "san": "d6",
    "note": "中央を支え、ビショップの退路も確保する堅実な一手。"
   },
   {
    "san": "Nc3",
    "note": "駒を組み上げる。"
   },
   {
    "san": "Nf6",
    "note": "e4をうかがいつつ展開。"
   },
   {
    "san": "Bc4",
    "note": "こちらもf7をにらむ位置へ。"
   },
   {
    "san": "Nc6",
    "note": "自然に展開。両者、キングの安全を見ながらの駒組みが続く。"
   }
  ],
  "en": {
   "title": "King's Gambit",
   "intro": "White offers a pawn on move two to open the center and attack quickly. This line uses the declined variation, showing that Black need not accept the pawn.",
   "takeaway": "A pawn offer does not have to be accepted. Prioritize the center and piece activity; a solid development plan can meet the gambit.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes central space."
    },
    {
     "san": "e5",
     "note": "Black answers symmetrically."
    },
    {
     "san": "f4",
     "note": "White offers the f-pawn to open lines and attack."
    },
    {
     "san": "Bc5",
     "note": "Black declines and develops the bishop to a useful diagonal aimed at f2."
    },
    {
     "san": "Nf3",
     "note": "White develops and attacks e5."
    },
    {
     "san": "d6",
     "note": "Black supports the center and gives the bishop a retreat square."
    },
    {
     "san": "Nc3",
     "note": "White develops another piece."
    },
    {
     "san": "Nf6",
     "note": "Black develops while watching e4."
    },
    {
     "san": "Bc4",
     "note": "White also places the bishop on the f7 diagonal."
    },
    {
     "san": "Nc6",
     "note": "Black develops naturally while both sides prepare for king safety."
    }
   ]
  }
 },
 {
  "id": "op_vienna",
  "cat": "opening",
  "title": "ウィーン・ゲーム",
  "fen": null,
  "intro": "2手目にナイトを先に跳ね、あとから f4 の攻めを含みに残すおおらかな戦い方。急がずに駒を出しつつ、いつでも中央で仕掛けられる柔軟さが魅力です。",
  "takeaway": "同じ攻めでも『順番』を変えると相手の対応が難しくなる。ナイトを先に出しておき、機を見て f4 で中央を開く。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e5",
    "note": "対称に応じる。"
   },
   {
    "san": "Nc3",
    "note": "ウィーン。まずナイトを跳ね、f4の攻めを含みに残す。"
   },
   {
    "san": "Nf6",
    "note": "対称に展開し、e4をうかがう。"
   },
   {
    "san": "f4",
    "note": "満を持して中央を開く。"
   },
   {
    "san": "d5",
    "note": "黒は中央で反撃するのが最善の応手。"
   },
   {
    "san": "fxe5",
    "note": "取る。"
   },
   {
    "san": "Nxe4",
    "note": "取り返し、中央のナイトを活用する。"
   },
   {
    "san": "Nf3",
    "note": "展開しつつ e5 を支える。"
   },
   {
    "san": "Be7",
    "note": "駒を出してキャスリングを準備。互いに戦える中盤へ。"
   }
  ],
  "en": {
   "title": "Vienna Game",
   "intro": "White develops the knight on move two and keeps the option of f4. It is a flexible way to develop before deciding how to challenge the center.",
   "takeaway": "Changing the move order can make the opponent's choices harder. Develop first, then use f4 when the position supports it.",
   "moves": [
    {
     "san": "e4",
     "note": "White takes central space."
    },
    {
     "san": "e5",
     "note": "Black answers symmetrically."
    },
    {
     "san": "Nc3",
     "note": "The Vienna move: develop the knight and keep f4 in reserve."
    },
    {
     "san": "Nf6",
     "note": "Black develops and eyes e4."
    },
    {
     "san": "f4",
     "note": "White now commits to f4 and opens a central fight."
    },
    {
     "san": "d5",
     "note": "Black counterattacks in the center with ...d5."
    },
    {
     "san": "fxe5",
     "note": "White captures the e5 pawn."
    },
    {
     "san": "Nxe4",
     "note": "Black recaptures with the knight and centralizes it."
    },
    {
     "san": "Nf3",
     "note": "White develops while supporting e5."
    },
    {
     "san": "Be7",
     "note": "Black develops and prepares to castle; a playable middlegame is coming."
    }
   ]
  }
 },
 {
  "id": "op_petrov",
  "cat": "opening",
  "title": "ペトロフ・ディフェンス",
  "fen": null,
  "intro": "相手が e5 を取りにきたら、自分も e4 を取り返しにいく『やり返す』受け方。対称的で手堅く、まず駒損をしない安全運転を学べる守りの定跡です。",
  "takeaway": "攻められたら守るだけでなく、同じ手で『やり返す』のも有力。対称的に応じて駒得を与えず、静かに好形を作る。",
  "moves": [
   {
    "san": "e4",
    "note": "中央を取る。"
   },
   {
    "san": "e5",
    "note": "対称に応じる。"
   },
   {
    "san": "Nf3",
    "note": "e5に当てて展開。"
   },
   {
    "san": "Nf6",
    "note": "守らずに、こちらも e4 に当て返すのがペトロフ。"
   },
   {
    "san": "Nxe5",
    "note": "取ってみる。"
   },
   {
    "san": "d6",
    "note": "すぐ取り返さず、まずナイトを追い返す。"
   },
   {
    "san": "Nf3",
    "note": "退く。"
   },
   {
    "san": "Nxe4",
    "note": "ここで取り返し、駒の数は互角に。"
   },
   {
    "san": "d4",
    "note": "中央を広げて主導権を取りにいく。"
   },
   {
    "san": "d5",
    "note": "黒も中央を張って、ナイトの足場を支える。堅い対称形。"
   }
  ],
  "en": {
   "title": "Petrov Defense",
   "intro": "When White attacks e5, Black attacks e4 in return. The result is symmetrical and solid, making it a useful lesson in meeting an attack with counterplay.",
   "takeaway": "You do not always have to defend passively. A direct counterattack can restore balance while keeping the position coordinated.",
   "moves": [
    {
     "san": "e4",
     "note": "White claims the center."
    },
    {
     "san": "e5",
     "note": "Black answers symmetrically."
    },
    {
     "san": "Nf3",
     "note": "The knight attacks e5 while developing."
    },
    {
     "san": "Nf6",
     "note": "Black attacks e4 instead of defending e5: the Petrov idea."
    },
    {
     "san": "Nxe5",
     "note": "White takes the pawn."
    },
    {
     "san": "d6",
     "note": "Black first drives the knight away rather than recapturing immediately."
    },
    {
     "san": "Nf3",
     "note": "The knight retreats."
    },
    {
     "san": "Nxe4",
     "note": "Black now recaptures; the pawn count is equal again."
    },
    {
     "san": "d4",
     "note": "White expands in the center."
    },
    {
     "san": "d5",
     "note": "Black contests the center and gives the knight a stable base."
    }
   ]
  }
 },
 {
  "id": "cb_boden",
  "cat": "combo",
  "title": "ボーデン・メイト(二枚のビショップ)",
  "fen": "2kr4/3p4/8/8/2B2B2/8/8/6K1 w - - 0 1",
  "intro": "二枚のビショップが、交差する斜めのラインからキングを挟み撃ちにする華麗な詰み。片方が正面からチェックし、もう片方が横の逃げ道を封じます。クイーンサイドに囲ったキングが引っかかりやすい形です。",
  "takeaway": "二枚のビショップの斜めが交差する所に相手のキングがいないか探す。相手自身の駒が逃げ道をふさいでいれば、二枚だけで詰む。",
  "moves": [
   {
    "san": "Ba6#",
    "note": "ビショップが a6-c8 の斜めからチェック。もう一枚のビショップが b8・c7 の逃げ道を封じ、d7 は自分のポーン、d8 は自分のルークでふさがっているのでチェックメイト。"
   }
  ],
  "en": {
   "title": "Boden's Mate",
   "intro": "Two bishops can cross their diagonals to trap a king. One gives the check while the other covers the escape squares, often against a king boxed in on the queenside.",
   "takeaway": "Look for crossing bishop diagonals and escape squares blocked by the defender's own pieces. Two bishops can be enough when the net is complete.",
   "moves": [
    {
     "san": "Ba6#",
     "note": "The bishop checks along a6-c8. The second bishop covers b8 and c7; d7 and d8 are occupied by Black's own pieces, so it is mate."
    }
   ]
  }
 },
 {
  "id": "cb_decoy",
  "cat": "combo",
  "title": "デコイ(おびき出し)",
  "fen": "3q1rk1/6pp/8/4N3/8/8/2B5/6K1 w - - 0 1",
  "intro": "相手のキングを、こちらの都合のいいマスへ『おびき出す』戦術。チェックでキングを狙いのマスへ追い込み、そこでナイトのフォークを炸裂させてクイーンを頂きます。",
  "takeaway": "『あの1マスにキングがいればフォークで勝てる』を先に見つける。チェックでキングをそのマスへ誘導してから、狙いの一撃を放つ。",
  "moves": [
   {
    "san": "Bb3+",
    "note": "ビショップのチェック。f7はビショップ自身の利き、f8はルークにふさがれている。ここではキングがh8へ逃げる変化を見る。"
   },
   {
    "san": "Kh8",
    "note": "キングは隅へ。これでナイトのフォーク網に入った。"
   },
   {
    "san": "Nf7+",
    "note": "ナイトが跳ねてチェック。同時に d8 のクイーンもフォーク(両取り)している。"
   },
   {
    "san": "Kg8",
    "note": "ここではキングをg8へ戻す変化を見る。ルークでナイトを取る応手もあるので、フォークは相手の応手を読んで使う。"
   },
   {
    "san": "Nxd8+",
    "note": "狙い通りクイーンを頂き、ビショップの利きも開いてチェック。キングをおびき出してからのフォークが決まった。"
   }
  ],
  "en": {
   "title": "Decoy",
   "intro": "A decoy lures an enemy piece, often the king, onto a square where a tactic works. This example uses a check to invite the king toward a knight fork.",
   "takeaway": "Find the square where the fork works first. Then look for a forcing check that encourages the king to go there. The opponent may have alternatives, so calculate them.",
   "moves": [
    {
     "san": "Bb3+",
     "note": "The bishop checks. The bishop controls f7 and the rook occupies f8; this line follows the king's retreat to h8."
    },
    {
     "san": "Kh8",
     "note": "The king goes to the corner and enters the knight's tactical net."
    },
    {
     "san": "Nf7+",
     "note": "The knight checks and attacks the queen on d8 at the same time."
    },
    {
     "san": "Kg8",
     "note": "This line follows Kg8. Black can also try Rxf7, so the fork depends on the opponent's reply."
    },
    {
     "san": "Nxd8+",
     "note": "The knight takes the queen with check, also opening the bishop's line to the king."
    }
   ]
  }
 },
 {
  "id": "eg_underpromo",
  "cat": "endgame",
  "title": "アンダープロモーション(ナイトへの昇格)",
  "fen": "8/4P1k1/3q4/8/8/8/8/6K1 w - - 0 1",
  "intro": "昇格は必ずクイーンが得とは限りません。ときには『ナイトに昇格』した方が、チェックやフォークが決まって一気に勝てることがあります。形にとらわれない発想を学びましょう。",
  "takeaway": "昇格のとき、クイーン以外の駒が『チェック』や『フォーク』になるなら、そちらが正解のこともある。目的は最強の駒より『一番効く駒』。",
  "moves": [
   {
    "san": "e8=N+",
    "note": "クイーンではなくナイトに昇格!昇格と同時にキングにチェックし、しかも d6 のクイーンもフォークしている。"
   },
   {
    "san": "Kf7",
    "note": "チェックを避けてキングが動く。"
   },
   {
    "san": "Nxd6+",
    "note": "そのままクイーンを頂く。クイーンに昇格していたら、この一撃はなかった。"
   }
  ],
  "en": {
   "title": "Underpromotion to a Knight",
   "intro": "A queen is not always the best promotion. Promoting to a knight can give check and create a fork that a queen would miss.",
   "takeaway": "When promoting, compare every legal piece. The goal is the piece that solves the position, not automatically the strongest piece.",
   "moves": [
    {
     "san": "e8=N+",
     "note": "The pawn promotes to a knight with check and forks the queen on d6."
    },
    {
     "san": "Kf7",
     "note": "The king moves to answer the check."
    },
    {
     "san": "Nxd6+",
     "note": "The new knight captures the queen. A queen promotion would not create this fork."
    }
   ]
  }
 },
 {
  "id": "eg_connected",
  "cat": "endgame",
  "title": "連結パスポーン(二枚の通過ポーン)",
  "fen": "6k1/8/1PP5/8/8/8/8/6K1 w - - 0 1",
  "intro": "隣り合った二枚の通過ポーンは、互いをかばい合えるのでとても強力。相手のキングが遠ければ、支え合いながら進んで一枚を昇格させられます。",
  "takeaway": "連結したパスポーンは『片方が進み、もう片方が守る』の連係で前進する。相手のキングが届かないうちに、手を取り合って昇格をめざす。",
  "moves": [
   {
    "san": "c7",
    "note": "前のポーンを進める。隣の b6 ポーンがこの c7 を守っているので取られない。"
   },
   {
    "san": "Kf7",
    "note": "キングが追いかけるが遠い。"
   },
   {
    "san": "b7",
    "note": "今度は後ろのポーンも上がる。二枚が最終列の一歩手前にそろった。"
   },
   {
    "san": "Ke7",
    "note": "間に合わない。"
   },
   {
    "san": "c8=Q",
    "note": "昇格!二枚が支え合いながら進み、キングに追いつかれる前に女王が生まれた。"
   }
  ],
  "en": {
   "title": "Connected Passed Pawns",
   "intro": "Two adjacent passed pawns are powerful because they can protect one another. If the opposing king is too far away, they can advance as a team and promote.",
   "takeaway": "Advance connected passed pawns as a unit: one moves while the other supports it. Keep moving before the enemy king arrives.",
   "moves": [
    {
     "san": "c7",
     "note": "The front pawn advances. The b6 pawn protects c7, so the king cannot take it."
    },
    {
     "san": "Kf7",
     "note": "The king chases, but is too far away."
    },
    {
     "san": "b7",
     "note": "The rear pawn advances; both pawns are now one step from promotion."
    },
    {
     "san": "Ke7",
     "note": "The king is too late."
    },
    {
     "san": "c8=Q",
     "note": "The front pawn promotes while the two pawns support one another."
    }
   ]
  }
 },
 {
  "id": "cb_hanging",
  "cat": "combo",
  "title": "【きほん】ハンギングピース(タダの駒)",
  "fen": "6k1/5ppp/8/r7/8/8/5PPP/Q5K1 w - - 0 1",
  "intro": "戦術のいちばんの基本は『相手の駒が守られているか』を見ること。誰にも守られていない駒(ハンギング・ピース)は、ただで頂けます。まずはこれを毎回チェックする習慣をつけましょう。",
  "takeaway": "指す前に必ず『相手の駒で守られていないものはないか』を見る。守りのない駒を見つけたら、取れるかどうかを確かめる。",
  "moves": [
   {
    "san": "Qxa5",
    "note": "a5のルークは誰にも守られていない『タダの駒』。クイーンで頂いてルークまるまる得。派手な手筋より、まずこれを見逃さないことが上達の近道。"
   }
  ],
  "en": {
   "title": "Hanging Pieces: The Basic Habit",
   "intro": "The most basic tactical question is whether the opponent's pieces are defended. A piece with no defenders may be hanging and can often be won for free.",
   "takeaway": "Before every move, scan for undefended enemy pieces. Then verify that your capture is safe before taking.",
   "moves": [
    {
     "san": "Qxa5",
     "note": "The rook on a5 has no defender. The queen can take it, winning a full rook. Spotting this consistently matters more than flashy combinations."
    }
   ]
  }
 },
 {
  "id": "cb_deflection",
  "cat": "combo",
  "title": "デフレクション(守り駒そらし)",
  "fen": "6k1/4rppp/8/7Q/2B5/8/8/4R1K1 w - - 0 1",
  "intro": "守り駒に二つの仕事をさせて『そらす』戦術。e7のルークは、f7のポーンとe筋(バックランク)の両方を守る働き者です。片方の仕事をさせれば、もう片方が手薄になります。",
  "takeaway": "『二つの役目を持つ守り駒(オーバーロード)』を探す。そこへ犠牲を打ち込んで役目を一つ放棄させれば、狙いが通る。",
  "moves": [
   {
    "san": "Qxf7+",
    "note": "クイーンをf7に切り込む!c4のビショップがf7を支えているので、キングでは取り返せない。"
   },
   {
    "san": "Rxf7",
    "note": "ここではルークで取り返す変化を見る。この瞬間、ルークはe筋の守りを離れてしまう。"
   },
   {
    "san": "Re8#",
    "note": "がら空きになったe筋にルークが飛び込んでチェックメイト。守り駒を『そらす』狙いが決まった。"
   }
  ],
  "en": {
   "title": "Deflection",
   "intro": "Deflection makes a defender abandon one of its duties. The rook on e7 protects both the f7 pawn and the e-file, so forcing it to handle one duty can expose the other.",
   "takeaway": "Look for an overloaded defender. A sacrifice can force it to leave one assignment, allowing the real threat to succeed.",
   "moves": [
    {
     "san": "Qxf7+",
     "note": "The queen enters on f7. The bishop on c4 protects f7, so the king cannot take the queen."
    },
    {
     "san": "Rxf7",
     "note": "This line follows Rxf7. The rook has now left the e-file to capture."
    },
    {
     "san": "Re8#",
     "note": "The rook enters on e8 with mate after the defender has been deflected."
    }
   ]
  }
 },
 {
  "id": "cb_windmill",
  "cat": "combo",
  "title": "【上級】ウィンドミル(風車)",
  "fen": "5r1k/1pp3Rp/8/q7/8/8/1B6/6K1 w - - 0 1",
  "intro": "ルークとビショップが組んで、チェックと駒取りを風車のようにぐるぐる繰り返す豪快な技。ルークが動くたびに後ろのビショップのチェックが『発見』されるので、相手は逃げるだけで何もできません。",
  "takeaway": "大駒の前に自分の駒があるとき、それを動かせばディスカバードチェックになる。チェック→駒取り→またチェックを繰り返し、相手の駒を刈り取っていく。",
  "moves": [
   {
    "san": "Rxc7+",
    "note": "ルークが7段目のポーンを取りながら、後ろのビショップのチェックを発見(ディスカバードチェック)。黒には複数の対応があるが、ここではKg8を選ぶ。"
   },
   {
    "san": "Kg8",
    "note": "h7は自分のポーン。ここではキングをg8へ逃がす。"
   },
   {
    "san": "Rg7+",
    "note": "ルークが戻ってチェック。ビショップに守られているので取れない。キングはまた隅へ。"
   },
   {
    "san": "Kh8",
    "note": "h8へ押し戻される。"
   },
   {
    "san": "Rxb7+",
    "note": "風車が一回転。またポーンを刈り取りながらディスカバードチェック。ここでも別の応手はあるが、同じ流れを選ぶ。"
   },
   {
    "san": "Kg8",
    "note": "同じようにキングをg8へ逃がす。"
   },
   {
    "san": "Rg7+",
    "note": "また戻ってチェック。相手は逃げるだけで、こちらは駒を稼ぎ続ける。"
   },
   {
    "san": "Kh8",
    "note": "隅へ。"
   },
   {
    "san": "Rg5+",
    "note": "最後にルークを5段目へ引いてディスカバードチェック。しかもa5のクイーンをにらんでいる。"
   },
   {
    "san": "Qe5",
    "note": "ここではクイーンをe5に差し出して斜めのチェックを止める変化を見る。"
   },
   {
    "san": "Rxe5",
    "note": "そのクイーンを頂いて風車は終了。チェックを利用して駒を刈り取り続ける、豪快な必殺技。"
   }
  ],
  "en": {
   "title": "Windmill",
   "intro": "A windmill repeats discovered checks and captures in a cycle. The rook moves out of the bishop's line, checks are answered, and the rook returns to take another piece.",
   "takeaway": "When a piece blocks a bishop or rook, consider a discovered check. Repeat check, capture, and check when the position allows it; do not assume every reply is forced.",
   "moves": [
    {
     "san": "Rxc7+",
     "note": "The rook captures on c7 and reveals the bishop's check. Black has several replies; this line chooses Kg8."
    },
    {
     "san": "Kg8",
     "note": "The h7 pawn blocks the corner, so the king escapes to g8 in this line."
    },
    {
     "san": "Rg7+",
     "note": "The rook returns with check. The bishop protects it, so the king moves away."
    },
    {
     "san": "Kh8",
     "note": "The king is pushed back to h8."
    },
    {
     "san": "Rxb7+",
     "note": "The windmill turns again: the rook captures b7 while revealing another discovered check. Other defenses exist, but this line repeats the pattern."
    },
    {
     "san": "Kg8",
     "note": "The king escapes to g8 again."
    },
    {
     "san": "Rg7+",
     "note": "The rook returns with another check and continues harvesting material."
    },
    {
     "san": "Kh8",
     "note": "The king goes back to the corner."
    },
    {
     "san": "Rg5+",
     "note": "The rook moves to the fifth rank, revealing the bishop's check and attacking the queen on a5."
    },
    {
     "san": "Qe5",
     "note": "This line interposes the queen on e5 to stop the diagonal check."
    },
    {
     "san": "Rxe5",
     "note": "The rook takes the queen. The windmill ends after using checks to win material."
    }
   ]
  }
 },
 {
  "id": "eg_stalemate",
  "cat": "endgame",
  "title": "【きほん】ステイルメイトに注意",
  "fen": "7k/5K2/8/8/8/8/8/6Q1 w - - 0 1",
  "intro": "大優勢なのに引き分けにしてしまう最大の落とし穴が『ステイルメイト』。相手がチェックされていないのに動ける手がまったく無いと、勝ちではなく引き分けになります。詰ませるときこそ慎重に。",
  "takeaway": "とどめの前に『相手に動ける手が残るか』を確認する。逃げ道を消すのはチェックをかけながら行う。ここで Qg6? とすると相手は動けず引き分けになってしまう。",
  "moves": [
   {
    "san": "Qg7#",
    "note": "クイーンをキングの隣へ。f7の自分のキングが g7 を守っているので取られず、チェックメイト。もし Qg6 としていたら、黒はチェックされていないのに動く手が無くステイルメイト(引き分け)だった。"
   }
  ],
  "en": {
   "title": "Watch for Stalemate",
   "intro": "Stalemate is the classic way to turn a winning position into a draw. If the side to move is not in check and has no legal move, the game is drawn.",
   "takeaway": "Before the final move, check that the opponent still has a legal move. Remove escape squares while giving check when possible. Qg6? here would stalemate.",
   "moves": [
    {
     "san": "Qg7#",
     "note": "The queen moves next to the king and gives mate. The king on f7 protects g7. Qg6 instead would leave Black with no move but no check: stalemate."
    }
   ]
  }
 },
 {
  "id": "eg_lucena",
  "cat": "endgame",
  "title": "【上級】ルセナ(橋を架ける)",
  "fen": "4K3/4P1k1/8/8/8/8/r7/5R2 w - - 0 1",
  "intro": "ルーク+ポーン対ルークの終盤で、最も重要な勝ち方が『ルセナのポジション』。相手のルークの連続チェックを、自分のルークで受け止める『橋』を架けて、ポーンを昇格させます。",
  "takeaway": "まず自分のルークを4段目に置いておくのがカギ。キングがチェックされたら、その4段目のルークをキングの前に差し出して『橋』にすれば、チェックが止まって昇格できる。",
  "moves": [
   {
    "san": "Rf4",
    "note": "橋の準備。ルークをあらかじめ4段目に置くのがルセナの要点。"
   },
   {
    "san": "Ra1",
    "note": "黒は様子を見る。"
   },
   {
    "san": "Kd7",
    "note": "キングがポーンの前から出て、昇格の道を空けにいく。"
   },
   {
    "san": "Rd1+",
    "note": "黒は連続チェックで邪魔をする。"
   },
   {
    "san": "Ke6",
    "note": "キングは前進しながらチェックをかわす。"
   },
   {
    "san": "Re1+",
    "note": "またチェック。"
   },
   {
    "san": "Kd5",
    "note": "ここで d5 に出るのがミソ。4段目のルーク(f4)をキングが守れる位置になる。"
   },
   {
    "san": "Rd1+",
    "note": "しつこくチェック。"
   },
   {
    "san": "Rd4",
    "note": "橋を架ける!ルークをキングの前に差し出す。d5のキングが守っているので、これでチェックが止まる。"
   },
   {
    "san": "Rxd4+",
    "note": "取っても…"
   },
   {
    "san": "Kxd4",
    "note": "キングが取り返して、じゃまなルークが消えた。"
   },
   {
    "san": "Kf7",
    "note": "黒のキングが急いで戻るが間に合わない。"
   },
   {
    "san": "e8=Q+",
    "note": "昇格成功!『橋を架ける』手筋で、ルーク終盤の基本形を勝ち切った。"
   }
  ],
  "en": {
   "title": "Lucena Position: Building a Bridge",
   "intro": "The Lucena position is a key winning method in rook-and-pawn versus rook endings. Use your rook as a bridge to shelter the king from checks and promote the pawn.",
   "takeaway": "Prepare the rook on the fourth rank. When checks arrive, place that rook in front of your king as a protected bridge, then promote.",
   "moves": [
    {
     "san": "Rf4",
     "note": "The rook goes to the fourth rank to prepare the bridge."
    },
    {
     "san": "Ra1",
     "note": "Black waits."
    },
    {
     "san": "Kd7",
     "note": "The king steps away from the pawn and clears the promotion route."
    },
    {
     "san": "Rd1+",
     "note": "Black starts checking from behind."
    },
    {
     "san": "Ke6",
     "note": "The king advances while avoiding the check."
    },
    {
     "san": "Re1+",
     "note": "Another check."
    },
    {
     "san": "Kd5",
     "note": "The king reaches d5, where it protects the rook on f4."
    },
    {
     "san": "Rd1+",
     "note": "Black checks again."
    },
    {
     "san": "Rd4",
     "note": "The rook builds the bridge on d4. The king on d5 protects it, so the check can be stopped."
    },
    {
     "san": "Rxd4+",
     "note": "Black captures the bridge."
    },
    {
     "san": "Kxd4",
     "note": "The king recaptures and removes the checking rook."
    },
    {
     "san": "Kf7",
     "note": "Black's king hurries back, but it is too late."
    },
    {
     "san": "e8=Q+",
     "note": "The pawn promotes with check. The bridge has converted the Lucena position."
    }
   ]
  }
 },
 {
  "id": "eg_philidor",
  "cat": "endgame",
  "title": "【上級】フィリドール(引き分けの受け)",
  "fen": "8/4k3/8/4PK2/8/8/r7/7R b - - 0 1",
  "intro": "ルーク終盤で負けそうなときの命綱が『フィリドールのポジション』。自分のルークを3段目(相手から見て6段目)に置いて相手のキングの前進を止め、ポーンが出てきたら後ろに回って連続チェックで引き分けに持ち込みます。",
  "takeaway": "劣勢のルーク終盤は『ルークを3段目に置く→ポーンが進んだら後ろからチェック』。これを知っていれば、負け筋の局面をきっちり引き分けにできる。",
  "moves": [
   {
    "san": "Ra6",
    "note": "まずルークを6段目に。白のキングの正面からの前進を止め、ポーンを進めさせて後ろからチェックする形へ誘う。"
   },
   {
    "san": "e6",
    "note": "白はやむなくポーンを進めるが…"
   },
   {
    "san": "Ra1",
    "note": "ポーンが出た瞬間、ルークを一気に後ろへ。ここから連続チェックが始まる。"
   },
   {
    "san": "Kg6",
    "note": "白のキングが前に出ようとすると…"
   },
   {
    "san": "Rg1+",
    "note": "後ろからチェック。"
   },
   {
    "san": "Kf5",
    "note": "逃げても…"
   },
   {
    "san": "Rf1+",
    "note": "またチェック。"
   },
   {
    "san": "Ke5",
    "note": "どこへ逃げても…"
   },
   {
    "san": "Re1+",
    "note": "チェックが続く。"
   },
   {
    "san": "Kd5",
    "note": "白のキングに隠れる場所はない。"
   },
   {
    "san": "Rd1+",
    "note": "延々とチェックが続き、白は前進できないまま引き分けに。負け局面を守り切る、覚えておくべき受けの技術。"
   }
  ],
  "en": {
   "title": "Philidor Position: The Drawing Defense",
   "intro": "The Philidor position is a vital drawing method in rook endings. The defending rook controls the rank in front of the enemy king, then checks from behind once the pawn advances.",
   "takeaway": "Keep the rook on the checking rank while the king is in front. When the pawn advances, move behind it and give checks from a distance.",
   "moves": [
    {
     "san": "Ra6",
     "note": "The rook reaches the sixth rank. It prevents the white king from making a direct advance and invites the pawn to move."
    },
    {
     "san": "e6",
     "note": "White advances the pawn, but this helps the defensive plan."
    },
    {
     "san": "Ra1",
     "note": "The rook moves behind the pawn. The checking sequence begins."
    },
    {
     "san": "Kg6",
     "note": "The white king tries to advance."
    },
    {
     "san": "Rg1+",
     "note": "The rook checks from behind."
    },
    {
     "san": "Kf5",
     "note": "The king steps away, but the checks continue."
    },
    {
     "san": "Rf1+",
     "note": "Another check."
    },
    {
     "san": "Ke5",
     "note": "The king tries another route."
    },
    {
     "san": "Re1+",
     "note": "The checking rook shifts again."
    },
    {
     "san": "Kd5",
     "note": "The king has no shelter that ends the checks."
    },
    {
     "san": "Rd1+",
     "note": "The rook keeps checking, so White cannot make progress. The lost position is held to a draw."
    }
   ]
  }
 },
 {
  "id": "cb_zwischenzug",
  "cat": "combo",
  "title": "ツヴィッシェンツーク(中間手)",
  "fen": "6k1/5ppp/3b1n2/3N4/4P3/8/5PPP/6K1 b - - 0 1",
  "intro": "取られたらすぐ取り返す——それが当たり前とは限りません。取り返す前に『もっと強い手』をはさむのがツヴィッシェンツーク(中間手)。相手が対応せざるを得ないチェックなどをはさむと、まるまる得をします。",
  "takeaway": "取り返す前に一呼吸。『先にチェックや大きな脅威をはさめないか?』を必ず考える。順番を変えるだけで得が増える。",
  "moves": [
   {
    "san": "Bxh2+",
    "note": "すぐNxd5と取り返すのではなく、先にチェックをはさむ!これが中間手。相手はまずチェックに対応しなければならない。"
   },
   {
    "san": "Kxh2",
    "note": "ここでは自然にビショップを取り返す変化を見る。Kh1やKf1など、別のチェック対応も合法。"
   },
   {
    "san": "Nxd5",
    "note": "ここで改めてナイトを取り返す。中間手のおかげで、h2のポーンがまるまる余分に得られた。"
   },
   {
    "san": "exd5",
    "note": "白も取り返して駒数は互角だが、黒はポーン1つ得している。順番を変えただけの差。"
   }
  ],
  "en": {
   "title": "Zwischenzug (In-Between Move)",
   "intro": "Capturing back immediately is not always best. A zwischenzug inserts a stronger move first, often a check, before making the expected recapture.",
   "takeaway": "Pause before recapturing. Ask whether a check or major threat can come first; changing the order can win an extra pawn.",
   "moves": [
    {
     "san": "Bxh2+",
     "note": "Instead of immediately playing Nxd5, Black inserts a check with Bxh2+. The opponent must answer the check first."
    },
    {
     "san": "Kxh2",
     "note": "This line naturally recaptures the bishop with Kxh2; Kh1 and Kf1 are also legal responses."
    },
    {
     "san": "Nxd5",
     "note": "Black now recaptures on d5. The in-between check has won the h2 pawn as an extra."
    },
    {
     "san": "exd5",
     "note": "White recaptures as well. The pieces are balanced, but Black has won one extra pawn by changing the order."
    }
   ]
  }
 },
 {
  "id": "cb_interference",
  "cat": "combo",
  "title": "インターフェアレンス(利きの遮断)",
  "fen": "6k1/r3b1pp/2PP4/8/8/8/8/6K1 w - - 0 1",
  "intro": "守っている駒と守られている駒の『あいだ』に駒を置いて、利きを断ち切る戦術。守り駒はそこにいるのに、線をふさがれて仕事ができなくなります。",
  "takeaway": "『どの線を通って守っているか』を見る。その線の途中に駒を置ければ、守り駒はいても守れない。",
  "moves": [
   {
    "san": "c7",
    "note": "ポーンを突き出して7段目の線を遮断!a7のルークは、この壁のせいで e7 のビショップを守れなくなった。しかもこのポーンは d6 のポーンが守っている。"
   },
   {
    "san": "Rxc7",
    "note": "ここではルークで遮断したポーンを取る変化を見る。"
   },
   {
    "san": "dxc7",
    "note": "取り返して、ルークをまるごと頂いた上にポーンが最終列の一歩手前へ。"
   },
   {
    "san": "Bd8",
    "note": "昇格を止めにビショップが回るが…"
   },
   {
    "san": "cxd8=Q+",
    "note": "そのビショップを取りながら昇格。利きを断つ一手が、すべての始まりだった。"
   }
  ],
  "en": {
   "title": "Interference",
   "intro": "Interference places a piece between a defender and its target, cutting the line of protection. The defender remains on the board but can no longer do its job.",
   "takeaway": "Trace the exact line by which a piece is defended. If you can occupy a square on that line, the target may become vulnerable.",
   "moves": [
    {
     "san": "c7",
     "note": "The pawn advances to c7 and blocks the seventh-rank line. The rook on a7 can no longer defend the bishop on e7; the pawn is protected by d6."
    },
    {
     "san": "Rxc7",
     "note": "This line follows Rxc7, capturing the interfering pawn."
    },
    {
     "san": "dxc7",
     "note": "The d-pawn recaptures, winning the rook and reaching c7 near promotion."
    },
    {
     "san": "Bd8",
     "note": "The bishop moves to d8 to stop promotion."
    },
    {
     "san": "cxd8=Q+",
     "note": "The pawn captures the bishop while promoting. The interference started the entire tactic."
    }
   ]
  }
 },
 {
  "id": "eg_wrongbishop",
  "cat": "endgame",
  "title": "まちがった色のビショップ(引き分け)",
  "fen": "7k/8/5K1P/8/8/8/8/3B4 w - - 0 1",
  "intro": "ビショップとポーンがあっても勝てないことがあります。端(ルーク)のポーンで、昇格マスの色を自分のビショップが利かせられないとき——これが『まちがった色のビショップ』。相手のキングが隅に居座るだけで引き分けです。",
  "takeaway": "端のポーンは昇格マスの色に注意。自分のビショップがその色を攻撃できないなら、相手のキングが隅に入るだけで引き分け。攻める側は追い出せず、受ける側はこれを狙う。",
  "moves": [
   {
    "san": "Kg6",
    "note": "キングを寄せて追い出そうとするが…"
   },
   {
    "san": "Kg8",
    "note": "黒のキングは隅の周りを動くだけでよい。h8の色(黒マス)は白の白マスビショップでは攻撃できない。"
   },
   {
    "san": "h7+",
    "note": "ポーンを進めてチェックしてみる。"
   },
   {
    "san": "Kh8",
    "note": "黒のキングは隅へ。ここが安全地帯。もう白は追い出す方法がない。"
   },
   {
    "san": "Kh6",
    "note": "キングを詰め寄せると——黒はチェックされていないのに動ける手がなく、ステイルメイト(引き分け)。ビショップの色が合っていれば勝てたのに、と悔やまれる典型例。"
   }
  ],
  "en": {
   "title": "Wrong-Colored Bishop: A Draw",
   "intro": "A bishop and pawn do not always win. With a rook pawn, if the bishop cannot control the promotion square's color, the defending king can hold the corner and draw.",
   "takeaway": "Check the color of the promotion square. If your bishop cannot attack that color, the defender may draw simply by reaching the corner.",
   "moves": [
    {
     "san": "Kg6",
     "note": "The king approaches, trying to drive the defender away."
    },
    {
     "san": "Kg8",
     "note": "The black king circles near the corner. h8 is a dark square, which the white light-squared bishop cannot attack."
    },
    {
     "san": "h7+",
     "note": "The pawn advances with check."
    },
    {
     "san": "Kh8",
     "note": "The king returns to h8, the safe corner. White has no way to force it out."
    },
    {
     "san": "Kh6",
     "note": "The king approaches again, but this move stalemates Black. With the correct-colored bishop, this ending would be won."
    }
   ]
  }
 },
 {
  "id": "eg_triangulation",
  "cat": "endgame",
  "title": "【上級】トライアンギュレーション(三角法)",
  "fen": "8/4k3/8/3KP3/8/8/8/8 w - - 0 1",
  "intro": "『同じ形で相手に手番を渡せたら勝ち』という局面があります。キングを三角形に動かして1手だけ余分に使えば、同じような形を相手の手番で作れることがあります。これが三角法(トライアンギュレーション)です。",
  "takeaway": "キングは3手で三角形に動くと元の位置に戻れる。相手のキングが2マスしか往復できないなら、この1手のズレで手番を押しつけられる(ツークツワンク)。",
  "moves": [
   {
    "san": "Kc4",
    "note": "三角形の一歩目。あえて遠回りする。"
   },
   {
    "san": "Kd7",
    "note": "ここでは黒のキングをd7へ戻す変化を選ぶ。黒にはKe6やKf7など別の応手もあり、三角法は相手の応手を読んで使う。"
   },
   {
    "san": "Kd4",
    "note": "三角形の二歩目。"
   },
   {
    "san": "Ke7",
    "note": "黒のキングも戻る。"
   },
   {
    "san": "Kd5",
    "note": "三角形を一周して元の位置へ。主要な駒の配置は最初と同じだが、今度は黒の手番。これがツークツワンクの狙い。"
   },
   {
    "san": "Kf7",
    "note": "黒はどこかへ動くしかなく、d6のマスから目を離してしまう。"
   },
   {
    "san": "Kd6",
    "note": "待っていた侵入!キングがポーンの前に出て、昇格の道を作った。"
   },
   {
    "san": "Kf8",
    "note": "黒はもう止められない。"
   },
   {
    "san": "e6",
    "note": "キングに守られてポーンが前進。"
   },
   {
    "san": "Ke8",
    "note": "黒のキングは必死に前へ。"
   },
   {
    "san": "e7",
    "note": "さらに前進。三角法の1手が勝敗を分けた。"
   }
  ],
  "en": {
   "title": "Triangulation",
   "intro": "Sometimes the winning idea is to give the opponent the move in the same position. A king can spend one extra tempo by walking a triangle and return with the move transferred.",
   "takeaway": "A three-move triangle returns the king to its starting square. That spare tempo can create zugzwang when the opposing king has no useful waiting move.",
   "moves": [
    {
     "san": "Kc4",
     "note": "The first step of the triangle deliberately takes the long way around."
    },
    {
     "san": "Kd7",
     "note": "This line returns Black's king to d7; Black also has alternatives such as ...Ke6 and ...Kf7, so calculate the opponent's best defense."
    },
    {
     "san": "Kd4",
     "note": "The second triangle step."
    },
    {
     "san": "Ke7",
     "note": "Black's king returns."
    },
    {
     "san": "Kd5",
     "note": "The white king completes the triangle. The main piece placement is restored, but it is now Black to move: the zugzwang idea."
    },
    {
     "san": "Kf7",
     "note": "Black must move and leaves d6 uncovered."
    },
    {
     "san": "Kd6",
     "note": "The white king enters through the opening and clears the promotion route."
    },
    {
     "san": "Kf8",
     "note": "Black cannot catch the pawn."
    },
    {
     "san": "e6",
     "note": "The pawn advances under the king's protection."
    },
    {
     "san": "Ke8",
     "note": "Black's king rushes forward."
    },
    {
     "san": "e7",
     "note": "The pawn advances again; the extra tempo decides the ending."
    }
   ]
  }
 }
];
