// English titles and ideas for PUZZLES, kept by generated-array index.
const PUZZLE_EN = [
  ['Hello from the Back Rank', 'The pawns in front of the king remove its escape squares. Invade the back rank with the rook!'],
  ['The End of the Corridor', 'A king boxed in by its own pawns is vulnerable on the back rank. Send in the rook for mate.'],
  ['The Closed Door', 'The queen can also finish a back-rank attack. Enter from the side against the king boxed in by pawns.'],
  ['Side Capture Mate', 'When a defending rook faces your rook, capture it. The capture opens a back-rank mate.'],
  ['The Other Door', 'The idea is the same when the king is on the edge: bring the rook to the back rank with no escape squares.'],
  ['A Strike in the Corner', 'Even a cornered king can be vulnerable on the back rank. If pawns block the exits, bring in the queen from the side.'],
  ['A Diagonal Gap', 'Combine the bishop diagonal with the queen. First seal the king’s diagonal escapes, then finish the attack.'],
  ['The Hidden Diagonal', 'Do not miss a distant bishop. A diagonal defender can make a queen invasion possible.'],
  ['The King with Epaulettes', 'When the king’s neighbors are blocked by its own rooks, the queen can remove the remaining escapes with rank and diagonal attacks.'],
  ['Caught in the Corner', 'The basic king-and-rook finish: use your king to remove escapes and the rook to seal the last rank.'],
  ['The Edge King', 'Hold the cornered king with your king, then finish with the rook. Learn the endgame pattern by doing it.'],
  ['The Queen’s Greeting', 'The king-and-queen finish: when the queen moves next to the king, your own king must protect it.'],
  ['The Queen on the Castle', 'Opposition between the kings is the key. Remove every escape before giving the queen check.'],
  ['Check from Afar', 'The queen can remove every escape from a distance. Box the king in with your king and the finish is safe.'],
  ['Knight in the Corner', 'The knight slips into the king’s shelter. A king surrounded by its own pieces is vulnerable to a knight check.'],
  ['The Arabian Trap', 'Rook and knight coordinate for an Arabian mate. A cornered king is mated when the knight removes its escape.'],
  ['The Rook Roller', 'The two-rook ladder: one rook seals an escape rank while the other gives check.'],
  ['Two-Rank Rocket', 'With one rook controlling the seventh rank, send the other to the eighth for the ladder-mate finish.'],
  ['The Top of the Ladder', 'Once one rook seals the seventh rank, move the other to the eighth. This is the basic two-rook mate.'],
  ['Scholar’s Mate', 'The opening trap known as Scholar’s Mate. f7 is a major weakness because only the king defends it here.'],
  ['The Fastest Mate', 'Fool’s Mate is the fastest checkmate. Carelessly opening the diagonals around the king can allow mate in two moves.'],
  ['The Corner King', 'When your king has removed the opponent’s escapes, the queen can step next to the king for mate.'],
  ['The Trapped Knight', 'A king surrounded by its own pieces is vulnerable to a knight invasion. Strike while every exit is blocked.'],
  ['The Boxed-In Knight', 'The king is surrounded by its own rooks and pawns. A knight invasion leaves no escape: smothered mate.'],
  ['From the Sky', 'A pawn can support the queen next to the king, making the checking queen untouchable.'],
  ['Rook Support', 'The seventh-rank rook protects g7. Confirm the support before sending the queen next to the king.'],
  ['Knight and Queen', 'The knight watches h7 and g8, supporting the queen. Use the supported check to finish the cornered king.'],
  ['The King Helps', 'A king-and-rook finish. Bring your king close first and drive the enemy king onto an edge square.'],
  ['Bring Up the King', 'A rook cannot mate alone. Bring your king close, remove the escapes, and then seal the last rank with the rook.'],
  ['Climb the Ladder', 'Use two rooks to drive the king up one rank at a time: seal a rank, then alternate checks.'],
  ['Twin-Tower Plan', 'Even from far apart, two rooks can build a ladder and drive the king to the edge.'],
  ['Build a Ladder', 'The two-rook ladder: seal one rank with one rook, then bring the other to the last rank.'],
  ['Drive to the Edge', 'Coordinate queen and king. Remove the escapes first, then finish with a protected queen check.'],
  ['The Queen Gift', 'If mate is visible, a queen sacrifice can be worthwhile. Remove the defender and follow through with the mating net.'],
  ['Finish with the Rook', 'A three-move king-and-rook finish: bring up your king, drive the enemy king to the edge, and seal it in.'],
  ['A Distant Ladder', 'Build a ladder with two rooks from a distance. Seal a rank, alternate checks, and push the king to the edge in three moves.'],
  ['Queen Net', 'Use the queen to narrow the escapes while bringing up your king. Practice calculating three moves ahead.'],
  ['Route to the Corner', 'Stay calm when chasing a cornered king. If you remove the escapes in the right order, mate comes in three moves.'],
];
