// 3Dモード用ドット絵データ(擬人化どうぶつ・宴会アイテム・馬車)
// 26x34px・陰影3階調(光源は左上)・チーム色は teams で差し替え
// 注意: この定義は末尾の ; を除いて厳密なJSON。tools/render_sprites.py がパースする。
const SPRITE_DATA = {
  "meta": { "width": 26, "height": 34, "baseline": 30 },
  "teams": {
    "w": { "A": "#d8555c", "L": "#ef8289", "D": "#a83a44", "a": "#e8b54a", "h": "#c86b5f", "H": "#e6a094", "G": "#9c4a40" },
    "b": { "A": "#5570bd", "L": "#8298d8", "D": "#3a4f92", "a": "#b8c4dc", "h": "#949fae", "H": "#c6d0dc", "G": "#626c7c" }
  },
  "chars": {
    "k": {
      "name": "ライオン",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#ece2d2", "p": "#f2a8a0",
               "f": "#eda14e", "F": "#f7c47f", "d": "#c97f33", "m": "#b5542a", "M": "#d97840",
               "n": "#8a4a34", "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#7a5030", "X": "#573822" },
      "art": [
        "........yy..yy..yy........",
        "........yYyyYyyyYy........",
        "........yAyyAyyAyy........",
        "........gggggggggg........",
        ".......mmMMMMMMMMmm.......",
        ".....mmmoooooooooommm.....",
        "....mmooFFFFFFffffoomm....",
        "...mmoFFFFFFffffffddomm...",
        "..mmoFFFFFffffffffdddomm..",
        ".mmoFFFFffffffffffddddomm.",
        ".mmoFFFFEeffffffEeffddomm.",
        ".mmoFFFFeeffffffeeffddomm.",
        ".mmoFfppwwwwnnwwwwppddomm.",
        ".mmoFffwwwwwoowwwwwfddomm.",
        "..mmoFffwwwwwwwwffdddomm..",
        "...mmoffffffffffffddomm...",
        "....mmoooooooooooooomm....",
        "......mmmMMMMMMMMmmm......",
        ".DDoLLLLAAAAAAAAAADDDDoDD.",
        ".DDoLLLLAAAAAAAAAADDDDoDD.",
        ".DDoLLLAAAAAAAAAAADDDDoDD.",
        ".DDoLLLAAAAAAAAAAADDDDoDD.",
        ".DDoaaaaaaaayYaaaaaaaaoDD.",
        ".DDoLLLAAAAAAAAAAADDDDoDD.",
        ".DDDoLLAAAAAAAAAADDDDoDDD.",
        ".DDDoaaaaaaaaaaaaaaaaoDDD.",
        ".DDD..offo......offo..DDD.",
        ".....oxxxo......oxxxo.....",
        ".....oxxxo......oxxxo.....",
        "....oxxxxo......oxxxxo....",
        "....oooooo......oooooo....",
        "..........................",
        "..........................",
        ".........................."
      ]
    },
    "q": {
      "name": "ねこ",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#ece2d2", "p": "#f2a8a0",
               "f": "#eec27f", "F": "#f8dfae", "d": "#d0a057", "n": "#e0879e",
               "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#7a5030", "X": "#573822" },
      "art": [
        "..........................",
        "..........................",
        ".....oo............oo.....",
        ".....ofo...yYy....ofo.....",
        ".....ofpo..yyyyy.opfo.....",
        ".....oooooooooooooooo.....",
        "......ooFFFFFFffffoo......",
        ".....oFFFFFFffffffddo.....",
        "....oFFFFFffffffffdddo....",
        "...oFFFFffffffffffddddo...",
        "...oFFFFEeffffffEeffddo...",
        "...oFFFFeeffffffeeffddo...",
        "...oFfppwwwwnnwwwwppddo...",
        "...oFffwwwwwoowwwwwfddo...",
        "....oFffwwwwwwwwffdddo....",
        ".....offffffffffffddo.....",
        "......oooooooooooooo......",
        "....oooooooooooooooooo....",
        "...oLLLLAAAAyYAAAADDDDo...",
        "...oLLLAAwwwwwwwwAADDDo...",
        "...oLLLAAwwwwwwwwAADDDo...",
        "...oLLLAAwwwwwwwwAADDDo...",
        "...oaaaAAwwwwwwwwAAaaao...",
        "...oLLLAAwwwwwwwwAADDDo...",
        "..oLLLLAAwwwwwwwwAADDDDo..",
        "..oLLLLAAAwwwwwwAAADDDDo..",
        "..oWaWaWaWaWaWaWaWaWaWao..",
        "..oooooooooooooooooooooo..",
        "......oxxo......oxxo......",
        "......oxxo......oxxo......",
        "......oooo......oooo......",
        "..........................",
        "..........................",
        ".........................."
      ]
    },
    "r": {
      "name": "くま",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#ece2d2", "p": "#f2a8a0",
               "f": "#a5754c", "F": "#c49a6c", "d": "#815732", "n": "#4c342a",
               "h": "#949fae", "H": "#c6d0dc", "G": "#626c7c",
               "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#7a5030", "X": "#573822" },
      "art": [
        ".......hh...hh...hh.......",
        ".......HHhhhhhhhhGG.......",
        ".......HhhhhhhhhhhG.......",
        "......ohhhhhhhhhhhho......",
        "......oGGGGGGGGGGGGo......",
        "........oooooooooo........",
        "......ooFFFFFFffffoo......",
        ".....oFFFFFFffffffddo.....",
        "....oFFFFFffffffffdddo....",
        "...oFFFFffffffffffddddo...",
        "...oFFFFEeffffffEeffddo...",
        "...oFFFFeeffffffeeffddo...",
        "...oFfppwwwnnnnwwwppddo...",
        "...oFffwwwwwoowwwwwfddo...",
        "....oFffwwwwwwwwffdddo....",
        ".....offffffffffffddo.....",
        "......oooooooooooooo......",
        "....oooooooooooooooooo....",
        "...oHHHHhhhhhhhhhhGGGGo...",
        "...oHHHhhhhhhhhhhhGGGGo...",
        "...oHHHhhhhhhhhhhhGGGGo...",
        "...oHHhhYhhhhhhYhhGGGGo...",
        "...oxxxxxxxxyYxxxxxxxxo...",
        "...oLLLAAAAAAAAAAADDDDo...",
        "....oLLAAAAAAAAAADDDDo....",
        "....oaaaaaaaaaaaaaaaao....",
        "......offo......offo......",
        ".....oxxxo......oxxxo.....",
        ".....oxxxo......oxxxo.....",
        "....oxxxxo......oxxxxo....",
        "....oooooo......oooooo....",
        "..........................",
        "..........................",
        ".........................."
      ]
    },
    "b": {
      "name": "ふくろう",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#ece2d2", "p": "#f2a8a0",
               "f": "#b48d5f", "F": "#d8bb8e", "d": "#8f6c42",
               "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#8a5f36", "X": "#573822" },
      "blinkChar": "W",
      "art": [
        "............LL............",
        "...........LLAA...........",
        "..........LAAAAD..........",
        ".........LAAAAADD.........",
        "........aaaaYaaaa.........",
        "......oLAAAAAAAAAAADo.....",
        "......ooFFFFFFffffoo..YY..",
        ".....oFFFFFFffffffddo.Yy..",
        "....oFFFFFffffffffdddo.x..",
        "...oFFWWWWWffffWWWWWddox..",
        "...oFFWEeWWffffWEeWWddox..",
        "...oFFWeeWWffffWeeWWddox..",
        "...oFFWWWWWfyyfWWWWWddox..",
        "...oFFFffffyYyfffffdddox..",
        "....oFfffffffffffddddo.x..",
        ".....offffffffffffddo..x..",
        "......oooooooooooooo...x..",
        "....oooooooooooooooooo.x..",
        "...oLLLLAAAAaaAAAADDDDox..",
        "...oLLLLAAAAaaAAAADDDDox..",
        "...oLLLLAAAAaaAAAADDDDox..",
        "...oLLLAAAAAaaAAAADDDDox..",
        "...oLLLAAAAAaaAAAADDDDox..",
        "...oLLLAAAAAaaAAAADDDDox..",
        "..oLLLLAAAAAaaAAAADDDDox..",
        "..oLLLLAAAAAaaAAAADDDDDo..",
        "..oLLLAAAAAAaaAAAAADDDDo..",
        "..oLLLAAAAAAaaAAAAADDDDo..",
        "..oaaaaaaaaaaaaaaaaaaaao..",
        "..oooooooooooooooooooooo..",
        "......oyyo......oyyo......",
        "..........................",
        "..........................",
        ".........................."
      ]
    },
    "n": {
      "name": "うま",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#ece2d2", "p": "#f2a8a0",
               "f": "#c08b52", "F": "#e3bd8a", "d": "#9c6c38", "m": "#6f4c2c", "M": "#8a6238", "n": "#573a22",
               "h": "#949fae", "H": "#c6d0dc", "G": "#626c7c",
               "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#7a5030", "X": "#573822" },
      "art": [
        "......oo..........oo......",
        ".....offo........offo.....",
        ".....offfo......offfo.....",
        "......offfo....offfo......",
        "......ommMMMM..offfo......",
        "......oooooooooooooo......",
        "......ooFFFFFFffmmoo......",
        ".....oFFFFFFffffffmmo.....",
        "....oFFFFFfffffffmmddo....",
        "...oFFFFffffffffffmmddo...",
        "...oFFFFEeffffffEeffmmo...",
        "...oFFFFeeffffffeeffmmo...",
        "...oFFffwwwwwwwwffddmmo...",
        "...oFffwnnwwwwnnwfddmmo...",
        "....oFffwwwwwwwwfddddo....",
        ".....offffffffffffddo.....",
        "......oooooooooooooo......",
        "....oooooooooooooooooo....",
        "...oHHhhAAAAAAAAAAhhGGo...",
        "...oLLLLAAAAAAAAAADDDDo...",
        "...oLLLAAAAAAAAAAADDDDo...",
        "...oLLLAAAAAAAAAAADDDDo...",
        "...oaaaaaaaayYaaaaaaaao...",
        "...oLLLAAAAAAAAAAADDDDo...",
        "....oLLAAAAAAAAAADDDDo....",
        "....oaaaaaaaaaaaaaaaao....",
        "......offo......offo......",
        ".....oxxxo......oxxxo.....",
        ".....oxxxo......oxxxo.....",
        "....oxxxxo......oxxxxo....",
        "....oooooo......oooooo....",
        "..........................",
        "..........................",
        ".........................."
      ]
    },
    "p": {
      "name": "ひよこ",
      "pal": { "o": "#33241d", "e": "#241812", "E": "#ffffff", "W": "#ffffff", "w": "#fff6d8", "p": "#f2a8a0",
               "f": "#ffd94f", "F": "#fff0a8", "d": "#e3b52f", "n": "#ef8f2c",
               "y": "#e8b54a", "Y": "#f8d98a", "g": "#b5822e", "x": "#9c6b3c", "X": "#6f4a26" },
      "art": [
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "..........................",
        "............xX............",
        "..........xxxxxx..........",
        ".........xxxxxxxx.........",
        "........xXXxxxxxxx........",
        "......ooFFFFFFffffoo......",
        ".....oFFFFFFffffffddo.....",
        "....oFFFFFffffffffdddo....",
        "...oFFFFEeffffffEeffddo...",
        "...oFFFFeeffffffeeffddo...",
        "...oFFfffffnnnffffffddo...",
        "...oFFffffffnffffffdddo...",
        "...oFppfffffffffffppddo...",
        "...oddFFFFffffffffddddo...",
        "...oaAAAAAAAAAAAAAAAAao...",
        "...oAALLAAAAAAAAAADDAAo...",
        "...offwwwwwwwwwwwwffddo...",
        "....offwwwwwwwwwwffddo....",
        ".....offffffffffffddo.....",
        "......oooooooooooooo......",
        ".......nn.......nn........",
        ".......nnn......nnn.......",
        "..........................",
        "..........................",
        ".........................."
      ]
    }
  },
  "items": {
    "meat": {
      "pal": { "o": "#3a2a22", "b": "#b05a34", "B": "#e08a54", "W": "#fff6e0" },
      "art": [
        "...oooooo...",
        "..obbbbbbo..",
        "WobBBBBBBboW",
        "WobBBBBBBboW",
        "..obbbbbbo..",
        "...oooooo..."
      ]
    },
    "cake": {
      "pal": { "o": "#3a2a22", "s": "#f6d7a0", "c": "#fff8f0", "i": "#e25a6a" },
      "art": [
        "....ii....",
        "...iiii...",
        ".cccccccc.",
        ".cccccccc.",
        ".ssssssss.",
        ".ssssssss.",
        ".oooooooo."
      ]
    },
    "mug": {
      "pal": { "o": "#3a2a22", "y": "#f2b53c", "W": "#fff8f0" },
      "art": [
        ".WWWWW...",
        "oyyyyyoo.",
        "oyyyyyo.o",
        "oyyyyyo.o",
        "oyyyyyoo.",
        "ooooooo.."
      ]
    },
    "apple": {
      "pal": { "o": "#3a2a22", "R": "#d84848", "g": "#6aa04a" },
      "art": [
        "....o...",
        "...og...",
        ".oRRRRo.",
        "oRRRRRRo",
        "oRRRRRRo",
        "oRRRRRRo",
        ".oRRRRo.",
        "..oooo.."
      ]
    },
    "table": {
      "pal": { "o": "#3a2a22", "T": "#d8a468", "t": "#a06a38" },
      "art": [
        "..oooooooooooooooo..",
        ".oTTTTTTTTTTTTTTTTo.",
        ".otttttttttttttttto.",
        "..oo............oo..",
        "..oo............oo..",
        "..oo............oo..",
        "...................."
      ]
    }
  },
  "carriage": {
    "pal": { "o": "#3a2a22", "f": "#b98757", "F": "#f0d6ae", "m": "#6a4a30", "n": "#6a4a30", "B": "#a06a38", "b": "#7c4a20", "y": "#e8c07a", "e": "#2a1c14", "W": "#ffffff" },
    "frames": [
      [
        "..............................mm......",
        ".............................mmoo.....",
        ".............................moffo....",
        ".....................mm.....offffo....",
        "....................mmmm...offfffo....",
        "oooooooooooooooo....mffffooffffeffo...",
        "oBBBBBBBBBBBBBBo....mfffffffffffffo...",
        "oBBBbbbbbbbbBBBo....mffffffffoFFno....",
        "oBBBbbbbbbbbBBBoooooffffffffffoFFo....",
        "oBBBBBBBBBBBBBBobbbbffffffffffoooo....",
        "oBBBBBBBBBBBBBBo...offffffffffo.......",
        ".oooooooooooooo....offffffffffo.......",
        "......oooo.........off.....offo.......",
        ".....oyyyyo........off......off.......",
        "....oyoyyoyo.......off......off.......",
        "....oyyooyyo.......off......off.......",
        "....oyoyyoyo......ooo......ooo........",
        ".....oyyyyo...........................",
        "......oooo............................",
        "......................................"
      ],
      [
        "..............................mm......",
        ".............................mmoo.....",
        ".............................moffo....",
        ".....................mm.....offffo....",
        "....................mmmm...offfffo....",
        "oooooooooooooooo....mffffooffffeffo...",
        "oBBBBBBBBBBBBBBo....mfffffffffffffo...",
        "oBBBbbbbbbbbBBBo....mffffffffoFFno....",
        "oBBBbbbbbbbbBBBoooooffffffffffoFFo....",
        "oBBBBBBBBBBBBBBobbbbffffffffffoooo....",
        "oBBBBBBBBBBBBBBo...offffffffffo.......",
        ".oooooooooooooo....offffffffffo.......",
        "......oooo..........off....off........",
        ".....oyyyyo.........off....off........",
        "....oyyoyoyo........off....off........",
        "....oyooyoyo.......off......off.......",
        "....oyyoyoyo......off........off......",
        ".....oyyyyo.......off........off......",
        "......oooo.......ooo........ooo.......",
        "......................................"
      ]
    ]
  }
};
