# -*- coding: utf-8 -*-
"""English metadata and move commentary for tools/games_gen.py.

The notes are rewritten while checking the position, rather than copied from
any published annotation.  Keep one note per SAN move so the generator can
validate the two arrays together.
"""


def E(title, white, black, opening, intro, takeaway, *notes):
    return {
        "title": title, "white": white, "black": black, "opening": opening,
        "intro": intro, "takeaway": takeaway, "notes": list(notes),
    }


EN = {
  "opera": E(
    "A Night at the Opera", "Paul Morphy", "Duke of Brunswick & Count Isouard",
    "Philidor Defense",
    "Known for the story that it was played during an opera performance, this game is a model attacking lesson. Morphy develops every piece quickly and punishes Black while several pieces remain out of play.",
    "Chess is about activity, not just material. Bring every piece into the attack before the opponent can coordinate.",
    "Advance the king pawn two squares: take central space and open the bishops' and queen's diagonals.",
    "Black answers symmetrically and contests the center.",
    "Develops the knight while attacking the e5-pawn, combining development with a threat.",
    "The pawn is defended, but the move is passive and restricts Black's bishop.",
    "The other central pawn advances to challenge the center.",
    "The bishop pins the knight, but the placement later becomes a target.",
    "White captures in the center and tests the relationship between Black's bishop and knight.",
    "Black chooses to recapture, but this helps White gain time and activity.",
    "The queen recaptures and reaches a useful square, eyeing f7 and b7.",
    "Black recaptures in turn. The material looks even, but White is ahead in development.",
    "The bishop targets the weak f7-square and gives the attack a clear direction.",
    "The knight develops while covering ideas based on Qh5.",
    "The queen attacks b7 and f7 at the same time, creating two difficult targets.",
    "The queen moves to defend f7, losing more time and coordination.",
    "White chooses development over a pawn grab and brings another piece into play.",
    "Black protects b7 and d5, but is forced into defense instead of an active plan.",
    "The last minor piece joins in and pins the f6-knight to the queen on d8.",
    "Black tries to counterattack, but the move only invites White's bishop forward.",
    "White gives up the knight to destroy c6 and open lines around the uncastled king.",
    "This is the selected line. Accepting the sacrifice lets White's attack accelerate; other choices would lead to different defenses.",
    "The bishop checks while targeting d7. Black's king still has no safe castling position.",
    "The knight steps in to defend, but becomes the next target.",
    "Castling places a rook on the d-file, concentrating force on the pinned defender.",
    "Black reinforces the pinned knight, but all of the pieces are tied to defensive duties.",
    "White removes a key defender and peels away another layer of the position.",
    "Black recaptures in this line, but the pressure on the d-file remains.",
    "The second rook joins the d-file, doubling the pressure on the pinned piece.",
    "The queen supports d7 and looks for a way to survive, but White's finish is close.",
    "White gives up another piece to preserve the pin and expose the black king.",
    "Black recaptures, leaving the d7-knight pinned and unable to move safely.",
    "The queen sacrifice is the final combination. If Black takes, the pinned knight must move and the d-file opens.",
    "Black accepts in the selected line, and the d-file is now completely open.",
    "The rook mates on d8. White's active army overwhelms Black's pieces, which never had time to coordinate.",
  ),
  "immortal": E(
    "The Immortal Game", "Adolf Anderssen", "Lionel Kieseritzky", "King's Gambit",
    "A symbol of Romantic-era chess. Anderssen gives up a bishop, two rooks, and finally the queen, then mates with the remaining minor pieces. The game shows how activity and concrete threats can outweigh material in a forcing attack.",
    "A sacrifice can be an investment: drive the enemy pieces into awkward roles and use the resulting coordination to build a mating net.",
    "Takes central space.", "Black replies symmetrically.",
    "The King's Gambit sacrifices a pawn to gain central control and attacking time.",
    "Black accepts the gambit.", "The bishop develops toward f7.",
    "The queen checks, drives the king from f1, and removes White's castling option.",
    "The king moves; White now commits to an attack rather than king safety.",
    "Black tries to drive the bishop away.", "White takes the pawn while keeping the bishop active.",
    "Develops while watching g4 and e4.",
    "White develops with tempo by attacking the black queen.",
    "The queen keeps its material, but its distant square contributes little to defense.",
    "Supports the center and opens the c1-bishop's diagonal.",
    "The knight protects f4 but is pushed toward the edge.",
    "Eyes an advance to f5 and puts pressure on the queen.",
    "The queen sidesteps the threat but remains poorly placed.",
    "The knight reaches an excellent outpost and eyes g7 and the surrounding squares.",
    "Black drives the bishop away.",
    "The pawn protects the knight on f5 and drives the h5-knight, despite opening lines near the king.",
    "The edge knight returns.",
    "The rook prepares to use the open g-file; this is a first hint of the coming sacrifice.",
    "Black takes the bishop and wins material, but White now begins a sequence of sacrifices.",
    "The pawn drives the queen and opens the h-file as another attacking route.",
    "The queen searches for a safe square.",
    "White drives it again; the black queen is forced from target to target.",
    "The queen returns in the selected line.",
    "The queen attacks the f6-knight and also eyes the f7-area, creating two pressures.",
    "The knight retreats to help defend, leaving Black's pieces poorly coordinated.",
    "White recovers the sacrificed f4-pawn while attacking the queen and rebuilding the attack.",
    "The queen is pulled into defensive work.",
    "White develops the last minor piece and points the whole army toward the king.",
    "Black tries to counterattack against the rook on g1.",
    "The knight centralizes with tempo against the queen; White is ready to sacrifice the rook.",
    "Black takes the rook, moving the queen far away from the defense.",
    "White sacrifices the bishop to remove a defender and prepare the mating net.",
    "Black takes the bishop, but White's attacking pieces are reaching their targets.",
    "The pawn blocks the queen's route back to the defense; Black cannot reorganize in time.",
    "Black takes the other rook, but those rooks are no longer relevant to the mating attack.",
    "The king steps away from check. White's king walks to safety under its own power.",
    "Black makes a late defensive attempt, but it is too slow.",
    "A minor piece checks and the mating net begins to close.",
    "The king moves in the selected line; other legal replies can lead to different continuations.",
    "The queen sacrifice is the final blow. If it is taken, the knight is freed from its pin.",
    "Black accepts the queen in this line.",
    "The bishop mates on e7. After giving up both rooks and the queen, White finishes with the light pieces alone.",
  ),
  "evergreen": E(
    "The Evergreen Game", "Adolf Anderssen", "Jean Dufresne", "Evans Gambit",
    "A game praised as one that never grows old. White finishes with a beautiful sequence of sacrifices, making it a useful example of building an attack and using combinations to remove defenders.",
    "Aim every attacking piece at the opponent's weak files and diagonals. A sacrifice can pull defenders away and make the final mating net possible.",
    "Takes central space.", "Black mirrors the move.", "Develops while attacking e5.",
    "Develops while defending the pawn.", "The bishop targets f7.", "Black develops symmetrically.",
    "The Evans Gambit sacrifices a pawn to prepare c3 and d4 quickly, buying central space and development.",
    "Black accepts the gambit.",
    "Prepares d4 and attacks the bishop, using the sacrificed pawn to gain time.",
    "The bishop preserves itself.",
    "White expands in the center and uses the open position to accelerate development.",
    "Black captures in the center.",
    "White castles and brings a rook toward the center; the attack is ready to grow.",
    "Black advances the pawn to disturb White's formation.",
    "The queen attacks f7 and b7 at once.", "The queen defends f7.",
    "The pawn drives the black queen while taking more central space.",
    "The queen retreats.",
    "The rook takes the open e-file and begins to control the center.",
    "The knight develops and prepares ideas such as ...f5.",
    "The bishop reaches a long diagonal, interferes with castling, and targets e7.",
    "Black starts a counterattack.", "White takes the pawn and keeps the pressure.",
    "Black attacks the queen.", "The queen retreats while watching d7 and a5.",
    "The bishop develops actively.",
    "White develops the last minor piece and prepares a central jump.",
    "Black also develops and eyes the knight on f3.",
    "The knight reaches the center and attacks f6 and d6; White's attacking setup is complete.",
    "The queen defends while looking for counterplay.",
    "White recovers the pawn and adds another attacking piece.",
    "The queen heads toward White's king and starts the final phase.",
    "The knight checks and invites gxf6, opening lines in front of the black king.",
    "Black accepts the capture in the selected line, weakening the king.",
    "The pawn advances against the exposed king.",
    "Black seeks counterplay against g2.",
    "The last rook joins the center and prepares a sacrifice on d7.",
    "Black takes the knight, but White's combination is stronger.",
    "White sacrifices the rook to remove a defender and pull out the black king.",
    "Black recaptures in the selected line.",
    "The queen sacrifice is the second blow; taking it allows the forcing checks to continue.",
    "Black accepts in this line.",
    "The bishop checks and drives the king into a narrow area.", "The king returns.",
    "Another check pushes the king farther in.", "The king moves to the selected square.",
    "The bishop captures on e7 and mates. Two sacrifices have created a complete mating net.",
  ),
  "reti_tartakower": E(
    "A Queen Sacrifice in One Flash", "Richard Réti", "Savielly Tartakower", "Caro-Kann-style setup",
    "In only eleven moves, White turns a central skirmish into a queen sacrifice that drags the black king into the open and finishes with two bishops. It is a compact lesson in forcing combinations.",
    "When the enemy king is stranded in the center, a sacrifice can draw it onto a vulnerable square where the minor pieces can coordinate a mate.",
    "Takes central space.",
    "The Caro-Kann setup prepares ...d5 to challenge e4.",
    "Expands in the center.", "Black challenges the center as planned.",
    "Attacks d5 and supports e4.", "Black captures in the center.",
    "White recaptures and places the knight on a strong central square.",
    "Develops while attacking the knight on e4.",
    "The queen moves forward deliberately, preparing the later sacrifice.",
    "Black strikes in the center, but the king remains uncastled.",
    "White captures, opening lines and making the exposed king more vulnerable.",
    "The queen checks while preparing to recover the pawn on e5.",
    "White answers the check and develops.",
    "Black recovers the pawn, but the king is still exposed in the center.",
    "Castling places a rook on the d-file and points it toward the black king.",
    "Black wins a knight, but this is the tactical mistake in the selected game.",
    "White offers the queen with check. If Black takes, the king is dragged onto a mating square.",
    "Black accepts in the selected line and the king is pulled to d8.",
    "The bishop checks and limits the king's escape squares.",
    "The king moves in the selected variation.",
    "The bishop returns to d8 and mates. White has given up the queen to finish with two bishops.",
  ),
  "lasker_thomas": E(
    "The King Hunt", "Edward Lasker", "George Thomas", "Dutch Defense",
    "A classic king hunt: after a queen sacrifice, Black's king is driven from its shelter across the board and finally mated. It demonstrates the power of a coordinated attack against an exposed king.",
    "Once the king's shelter has been broken, a sequence of checks can drive it far from safety. The attacking pieces must keep the escape squares controlled.",
    "Takes central space.",
    "A flexible move that can lead to Dutch- or French-style structures.",
    "Develops naturally.",
    "The Dutch Defense controls e4 and seeks active play, but it also weakens the area around the king.",
    "Continues development.", "Develops symmetrically.",
    "Pins the knight on f6.", "Prepares to break the pin.",
    "White exchanges deliberately to remove a defender near the black king.",
    "Black recaptures.",
    "White opens the center and prepares to attack the weakened king.",
    "Black takes in the center.",
    "White recaptures and centralizes the knight.",
    "Black tries to open the bishop's diagonal, but development is still behind.",
    "The knight jumps toward the key squares around g4 and f7.",
    "Black castles, but the newly castled king becomes the target.",
    "The bishop takes aim at h7 and completes the attacking setup.",
    "Black tries to defend, but the response is too slow.",
    "The queen attacks h7 twice and prepares the decisive sacrifice.",
    "Black attempts to meet the threat.",
    "The queen captures on h7 with check, sacrificing itself to tear open the king's shelter.",
    "Black accepts the queen in the selected line, pulling the king out.",
    "The knight checks and drives the king farther away.",
    "The king moves in the selected variation; the position may offer other legal choices.",
    "The second knight joins the checks.",
    "The king is driven toward the center.",
    "Even the pawn gives check, cutting off the return route.",
    "The king is forced deeper into White's half of the board.",
    "Another pawn check continues the chase.",
    "The king moves farther into the attack.",
    "The bishop checks and keeps the king boxed in.",
    "The king moves toward the corner.",
    "The rook joins the attack with check.",
    "The king reaches the corner.",
    "Castling completes the combination: the rook arrives on d1 and mates the king that has crossed the board.",
  ),
  "legal": E(
    "Legal's Trap", "Kermur de Legal", "Saint Brie", "Italian-style opening",
    "A classic pattern often taught as Legal's Mate. White allows the queen to be taken and then mates with the knights and bishop, turning a pin into a tactical resource.",
    "A pin is not absolute. When a mating sequence is available, a pinned piece may move if the concrete calculation supports it.",
    "Takes central space.", "Black mirrors the move.", "Attacks e5.", "Defends the pawn.",
    "The bishop targets f7.", "A solid, passive central defense.",
    "Develops another piece.",
    "The bishop pins the f3-knight and thinks the queen has been secured.",
    "White asks the bishop to decide between moving and exchanging.",
    "The bishop keeps the pin, but this allows the tactical idea.",
    "The knight moves despite the pin and attacks the queen; White is offering it as bait.",
    "Black takes the queen, but this is the decisive mistake.",
    "The bishop checks and draws the king into the mating net.",
    "The king chooses the line shown in this study.",
    "The knight mates on d5. White has given up the queen to finish with a coordinated group of minor pieces.",
  ),
  "canal": E(
    "The Peruvian Immortal", "Esteban Canal", "Anonymous (NN)", "Scandinavian Defense",
    "Known as the Peruvian Immortal, this attacking game ends with White sacrificing both rooks and the queen before mating with a single bishop. It also shows why an early castle is not automatically safe when the attacking lines point toward it.",
    "A castled king can still become a target. When a diagonal opens, a chain of sacrifices may suddenly make a mating attack possible.",
    "Takes central space.", "The Scandinavian immediately challenges e4.",
    "White captures in the center.", "Black recaptures with the queen, developing it early but also making it a target.",
    "Develops with tempo by attacking the queen.", "The queen retreats to a standard diagonal square.",
    "Expands in the center.", "Creates an escape square for the queen and a route for the bishop.",
    "Develops.", "Pins the f3-knight.",
    "Develops while looking toward c7.", "Opens the bishop's diagonal.",
    "Questions the pinned bishop.", "Black chooses the exchange.",
    "White recaptures and places the queen actively.",
    "Black uses the pin to seek counterplay.",
    "White quietly prepares to castle.", "Develops.",
    "The bishop is questioned again.",
    "Black castles long in the selected line, but that side of the board is exactly where White's attack is aimed.",
    "White captures the bishop and opens lines toward the black queen.",
    "Black takes a rook with check, but this is the first step in White's forcing sacrifice sequence.",
    "The king answers the check; White keeps the initiative.",
    "Black takes the second rook, but the captured rooks cannot return to defend the king.",
    "White sacrifices the queen with check. If Black accepts, the bishop's final check becomes decisive.",
    "Black accepts in this line, leaving the king's front completely open.",
    "The bishop mates on a6. White has given up both rooks and the queen to finish with one bishop.",
  ),
  "levitsky_marshall": E(
    "The Gold Coins Game", "Stepan Levitsky", "Frank Marshall", "French-style central battle",
    "Marshall's final move was so striking that spectators were said to have thrown gold coins onto the board; the story is disputed. The move is a famous example of a queen sacrifice that creates several simultaneous tactical threats.",
    "A piece placed on a seemingly safe square can create multiple mating or winning threats at once. Sometimes the strongest fork begins with a sacrifice.",
    "Takes central space.", "A flexible French-style setup.", "Expands further in the center.",
    "Challenges the center.", "Develops while attacking d5.", "Counters by striking at d4.",
    "Develops.", "Develops.", "White exchanges in the center.",
    "Black recaptures and opens the center.", "Develops and prepares to castle.",
    "Develops.", "White castles.", "Black also develops.",
    "The bishop pins the f6-knight and adds pressure.", "Black castles.",
    "White captures the pawn and disturbs Black's center.", "Develops while supporting d5.",
    "The knight centralizes.", "Black recovers the pawn and activates the bishop.",
    "White exchanges to damage Black's structure.",
    "Black recaptures, opening the f-file and creating a possible attacking route.",
    "The bishop targets e6.", "The queen becomes active.",
    "The bishop keeps pressure on e6.", "The rook occupies the open e-file.",
    "The queen improves its position.",
    "The bishop pins the knight and prepares a tactical attack.",
    "White exchanges to remove the pin.", "Black recaptures with the rook and eyes the f-file.",
    "The rook reaches the d-file.",
    "The queen strengthens the pin on the knight and accelerates the attack.",
    "White tries to defend.", "Black captures the pinned knight and damages the pawn structure.",
    "White recaptures, but the pawn structure is weakened.",
    "The queen captures deeply and enters the white position.",
    "White counterattacks by taking on d5.",
    "The knight reaches a strong square and attacks e2 and f3.",
    "The queen moves forward to seek counterplay.",
    "The second rook joins the f-file and concentrates the attack.",
    "White tries to defend.", "The rook attacks the queen and keeps the attack going.",
    "White tries to defend again.",
    "The rook captures the bishop and opens more lines around the king.",
    "White attempts a counterattack, but the next move ends the game.",
    "The queen is offered on an apparently safe square. Each of the three captures leads to a decisive fork or mating attack; White resigns.",
  ),
  "byrne_fischer": E(
    "The Game of the Century", "Donald Byrne", "Bobby Fischer", "Grünfeld Defense",
    "A historic game played by thirteen-year-old Bobby Fischer. He sacrifices the queen and uses the bishop, knight, and rooks so effectively that White's king remains under pressure while Black's own king stays safe.",
    "Coordination can outweigh the nominal value of a queen. If the enemy king remains under lasting pressure, the activity of several lesser pieces may be decisive.",
    "A flexible move that keeps the center undecided.", "Black replies symmetrically.",
    "The English Opening challenges the center from the side.",
    "A kingside fianchetto prepares to protect the king with the g7-bishop.",
    "Develops.", "The bishop reaches its long diagonal; it will remain important throughout the game.",
    "White occupies the center.", "Black castles early and secures the king.",
    "Develops while looking toward c7.",
    "The Grünfeld challenges White's broad center immediately.",
    "The queen attacks d5 and b7.",
    "Black captures and draws the queen forward while taking a pawn.",
    "White recaptures.", "Prepares ...b5 or ...d5 and opens a route for the bishop.",
    "White builds a large center and appears to have the space advantage.",
    "Develops and prepares a ...b6 counterattack.",
    "The rook takes the d-file.", "Black attacks the queen with tempo.",
    "The queen preserves itself.", "The bishop pins the f3-knight and increases pressure on the center.",
    "White tries to create counterplay.",
    "The knight attacks the queen and b2 at once, starting a sharp tactical sequence.",
    "The queen retreats in the selected line.",
    "Black exchanges on c3 and prepares to break through the center.",
    "White recaptures, but the pawn structure and king shelter are disturbed.",
    "Black takes the central pawn and sets tactical pressure around the pinned knight.",
    "White appears to win the queen, but this capture enters Fischer's combination.",
    "The queen remains active instead of defending passively, attacking the center and the white king.",
    "White tries to hold the position together.",
    "The knight checks and begins the forcing phase.",
    "White answers the check.",
    "The rook checks and drives the king away.",
    "The king moves in the selected line.",
    "The bishop offers itself, allowing White to take the queen while opening lines for Black's remaining pieces.",
    "White takes the queen, but Black's tactical compensation is decisive.",
    "The bishop recaptures with check and brings the light pieces into full activity.",
    "The king moves.", "The knight checks and keeps the king tied down.", "The king returns.",
    "The knight captures with check and gains more material.", "The king returns.",
    "The knight checks again and improves its position.", "The king returns.",
    "A discovered check also attacks the white queen and rook.", "The king returns.",
    "Black calmly recaptures the bishop. Black has material and every piece is active.",
    "White searches for counterplay.", "The rook attacks the queen and keeps the initiative.",
    "White takes the bishop, but Black wins a rook.",
    "The knight captures the rook, making Black's material advantage decisive.",
    "White creates luft for the king.", "The rook invades the second rank and collects material.",
    "The king moves away.", "The knight takes another pawn and reduces resistance.",
    "White tries to activate the rook.", "Black exchanges it and removes the counterplay.",
    "White checks to prolong the game.", "Black blocks calmly; the black king remains safe.",
    "White recaptures.", "The bishop takes an excellent diagonal and tightens the net around the king.",
    "White's knight searches for a square.",
    "The knight centralizes and prepares the final attack.",
    "White looks for counterplay, but has no effective plan.",
    "The pawn advances and completes the encirclement of the king.",
    "White can only make a waiting pawn move.", "Black preserves the formation.",
    "White makes a final attempt.", "The king improves its safety and prepares the finish.",
    "White's king returns to the corner.", "The bishop checks and begins the final sequence.",
    "The king moves.", "The knight checks and closes more escape squares.",
    "The king moves.", "The bishop checks again.", "The king moves.",
    "The bishop checks from the diagonal.", "The king moves toward the corner.",
    "The knight checks.", "The king moves to b1.",
    "The knight checks and forces the king onto the mating route.", "The king returns.",
    "The rook mates on c2. Fischer has sacrificed the queen and used the minor pieces to complete a legendary king hunt.",
  ),
  "deepblue_kasparov": E(
    "Deep Blue's Opening Trap Study", "Deep Blue", "Garry Kasparov", "Caro-Kann-inspired study line",
    "This is an arranged training line inspired by the famous Deep Blue–Kasparov story; it is not the score of Game 6 from the 1997 rematch. It uses a central knight sacrifice to teach how an opening trap can expose the king.",
    "Do not memorize an opening name and move order in isolation. Check the underlying tactic, and distinguish a study variation from the historical game score.",
    "Takes central space.", "The Caro-Kann prepares ...d5.", "White expands confidently in the center.",
    "Black challenges the center as planned.", "Develops while attacking d5.",
    "Black captures in the center.", "White recaptures and centralizes the knight.",
    "A solid move preparing ...Ngf6.",
    "The knight attacks f7 and e6 and begins an aggressive plan.",
    "The other knight develops naturally.", "The bishop joins the attack.",
    "Black blocks the bishop and strengthens the structure.",
    "The second knight develops and brings more force toward the king.",
    "Black tries to drive away the g5-knight, but this creates the tactical opportunity.",
    "The knight sacrifice on e6 is the key idea. Taking it opens the king and leaves Black with a difficult defense.",
    "Black declines the sacrifice in the selected line, but White's initiative is already strong.",
    "The machine castles calmly before continuing the attack.",
    "Black eventually captures the knight, opening the f- and e-files around the king.",
    "The bishop checks and Black also loses the right to castle.",
    "The king moves in the selected line and remains exposed in the center.",
    "White brings another piece into the attack with maximum efficiency.",
    "Black looks for a counterplay, but the attack is already advanced.",
    "White opens the flank to accelerate the attack.",
    "The bishop retreats to a long diagonal.",
    "The rook occupies the open e-file and targets e6 and e7.",
    "Black places a knight in the center to defend.",
    "The bishop retreats while preserving its pressure.",
    "The king moves toward a safer square.",
    "White exchanges on the queenside to keep the attack moving.",
    "Black recaptures in the selected line.",
    "The queen joins the attack and eyes b5 and the e-file.",
    "Black tries to defend.", "The bishop attacks e6 and keeps the defensive net under strain.",
    "Black captures the bishop, but the king and material remain in serious danger.",
    "The rook invades e7 and wins the queen; the black defense collapses.",
    "Black recaptures, but the position is hopeless and the game is resigned.",
    "A final push underlines the tactical finish shown in this study line.",
  ),
  "kasparov_topalov": E(
    "Kasparov's Immortal King Hunt", "Garry Kasparov", "Veselin Topalov", "Pirc Defense",
    "Often called Kasparov's Immortal, this is one of the great attacking games. Kasparov sacrifices a rook and drives the black king across the board before finishing the hunt with precise checks.",
    "When the winning continuation is concrete, material is not the only measure. Use checks to drive the king into open space, then calculate the next net accurately.",
    "Takes central space.", "The Pirc gives White the center while preparing counterplay with the g7-bishop.",
    "White builds a broad center.", "The knight challenges e4.",
    "Develops and supports the center.", "Prepares the fianchetto.",
    "The bishop develops to its long diagonal.",
    "Black's fianchetto bishop eyes the long diagonal.",
    "The queen prepares the h6 attack and castling long.",
    "Black prepares ...b5 and gives the king a flight square.",
    "Supports e4 and prepares the later g4-h4 advance.",
    "Black starts a counterattack on the opposite wing; both sides are racing toward the enemy king.",
    "The knight develops and prepares to castle.", "Black completes development and prepares ...c5 or ...e5.",
    "White exchanges the dangerous bishop and removes a defender near the king.",
    "Black recaptures in the selected line.",
    "The queen occupies an aggressive square near the black king.",
    "The bishop develops and watches e4 from the long diagonal.",
    "Prevents ...b4 and gives White's king more breathing room.",
    "Black strikes in the center and opens the position.",
    "White castles long and places the king on the opposite wing.",
    "The queen connects the pieces and prepares to castle long.",
    "The king steps to b1 for extra safety.", "Black reinforces the king's shelter.",
    "The knight heads toward b3 and central squares.",
    "Black castles long; both kings are now on opposite wings and the attack becomes a race.",
    "The knight reaches a useful square and eyes d4 and c5.",
    "Black exchanges in the center.", "White recaptures with the rook and contests the d-file.",
    "Black drives the rook away.", "The rook retreats temporarily to build pressure.",
    "The knight advances toward d5 and c4.", "White prepares the bishop and h3.",
    "The king moves to b8, the selected safety square.",
    "The knight attacks c6 and b7 from a5.",
    "The bishop retreats to the corner while keeping its diagonal.",
    "The bishop enters the attack and targets d7 and e6.",
    "Black pushes in the center, starting the tactical battle.",
    "The queen checks while moving to an active attacking square.",
    "The king moves toward the queenside and into danger.",
    "The final rook joins the attack; every white piece now faces the king.",
    "Black advances the central pawn and tries to blunt the knight.",
    "The knight centralizes and increases the pressure.",
    "Black captures the knight in the selected line.",
    "White recaptures, opening the e- and d-files toward the king.",
    "The queen tries to organize a defense.",
    "White sacrifices a rook. This is the decision that starts the cross-board king hunt.",
    "Black accepts the rook in the selected line.",
    "The other rook checks and drags the king away from its shelter.",
    "The king is forced forward in the selected variation.",
    "The queen checks again; the king cannot find a safe square.",
    "The king is driven all the way to a5 near White's camp.",
    "A pawn check restricts the remaining escape squares.",
    "The king reaches a4 on the edge of the board.",
    "The queen quietly tightens the net.",
    "Black counterattacks while trying to survive.",
    "The rook runs to the seventh rank and attacks the king on the a-file.",
    "The bishop blocks the attack.", "White captures and continues the chase.",
    "Black looks for counterplay.", "White recovers material without releasing the attack.",
    "The king runs deeper into White's position.", "The queen checks and keeps the king moving.",
    "The king moves still farther into White's camp.",
    "The pawn checks and removes another escape square.",
    "The king captures in the selected line.", "The queen checks again and closes the net.",
    "The king moves into the heart of White's position.",
    "Another queen check drives the king toward the first rank.",
    "The king reaches d1.", "The bishop quietly seals an escape square.",
    "Black makes a desperate counterattack.", "White keeps defense and attack coordinated.",
    "Black exchanges rooks.", "White recaptures the queen and secures a winning advantage.",
    "Black recaptures.", "White collects the distant rook as well.",
    "Black makes a final attempt.", "The queen retreats to stop the c-pawn.",
    "Black pushes the passed pawn and hopes for promotion.",
    "The queen checks while preparing to take the pawn.", "The king moves.",
    "White advances a pawn calmly while the king hunt is already decided.", "Black replies.",
    "The king moves to safety and prepares the finish.", "Black keeps trying to hold on.",
    "The queen balances defense and attack. Black has no useful move left and resigns after a king hunt from one side of the board to the other.",
  ),
  "paulsen_morphy": E(
    "Morphy's Queen Sacrifice", "Louis Paulsen", "Paul Morphy", "Four Knights Game",
    "This queen sacrifice helped make Morphy famous as a master of attack. He ignores pieces that are not helping the defense, gives up the queen, and finishes with a fast coordinated assault.",
    "Attacking strength comes from activity and speed, not only material count. When the winning continuation is clear, even the queen can be sacrificed before the defender coordinates.",
    "Takes central space.", "Black replies symmetrically.", "Develops while attacking e5.",
    "Defends the pawn while developing.", "The second knight joins the game.",
    "The Four Knights formation is complete and symmetrical.",
    "The bishop indirectly pressures the knight.", "Black develops symmetrically.",
    "White castles first and secures the king.", "Black castles too.",
    "White takes the central pawn.",
    "Black declines an immediate recapture and places a rook on the e-file for counterplay.",
    "White exchanges one knight.", "Black recaptures and opens the d-file and bishop's diagonal.",
    "The bishop retreats to a safer diagonal.", "Black gains time by attacking the bishop.",
    "The bishop retreats.", "Black recaptures the central pawn and removes the other knight.",
    "White recaptures.", "The rook takes control of the e-file.",
    "The bishop attacks the rook and tries to gain a tempo.",
    "The rook moves while keeping the later ...Rg6/...Rh6 attack in reserve.",
    "Supports the center.", "The queen penetrates deeply and ties down the white position.",
    "The pawn attacks the bishop to gain time.", "The bishop retreats while keeping its line.",
    "White seeks counterplay on the wing.", "Black captures the pawn.", "White recaptures.",
    "The bishop develops and prepares to bring the other rook to the e-file.",
    "The rook defends the second rank, but White's pieces are being pushed into passive roles.",
    "The second rook joins the attack; all of Black's pieces point toward the king.",
    "The queen tries to collect material, but it is far from the king.",
    "The queen sacrifice opens the g-file. If White accepts, the king shelter is torn open.",
    "White accepts in the selected line.",
    "The rook enters the open g-file with check; the main attack begins.",
    "The king moves to the corner.", "The bishop joins and prepares mating ideas on f1 and g2.",
    "White tries to defend.", "The bishop checks from g2.", "The king returns in the selected line.",
    "The bishop retreats with discovered check and also recovers a pawn.",
    "The king moves.", "The bishop returns with another check.", "The king returns.",
    "The bishop checks again and removes another escape square.", "The king moves to the corner.",
    "The bishop captures while tightening the mating net.", "White makes a final defensive move.",
    "Black captures the defender.", "White recaptures.",
    "The rook invades the second rank and prepares to finish.", "White struggles to defend.",
    "The other rook joins from the h-file.", "White makes a desperate pawn move.",
    "The bishop reaches the decisive square; White has no defense and resigns.",
  ),
  "steinitz_bardeleben": E(
    "Chasing the King", "Wilhelm Steinitz", "Curt von Bardeleben", "Italian Game",
    "A classic game by the first official world champion. A series of rook checks that cannot safely be captured drives the king to the edge, creating a famous lesson in a forcing king hunt.",
    "In a checking sequence, keep placing the attacking piece where the king cannot take it. Give the king legal squares, but use each move to build the next part of the net.",
    "Takes central space.", "Black replies symmetrically.", "Develops while attacking e5.",
    "Defends the pawn.", "The Italian bishop eyes f7.", "Black replies symmetrically.",
    "Prepares d4 and a larger center.", "Black attacks e4.", "White opens the center.",
    "Black captures.", "White recaptures and gains a broad center.",
    "The bishop checks while developing.", "White interposes and develops.",
    "Black strikes in the center.", "White captures.", "Black recaptures.",
    "White castles and secures the king.", "Black connects the pieces and supports d5.",
    "The bishop pins and increases pressure.", "Black breaks the pin.",
    "White exchanges to clarify the position.", "Black recaptures.", "White recaptures.",
    "The queen recaptures.", "The bishop exchanges and makes the king move.",
    "Black recaptures, but the king shelter is thinner.",
    "The rook occupies the open e-file and targets e7.",
    "Black creates luft, but the pawn move leaves a lasting weakness.",
    "The queen joins the e-file pressure.", "Black organizes the defense.",
    "The second rook reaches a strong square; the whole army points toward the king.",
    "Black prevents the knight from reaching d5.",
    "White pushes anyway and opens the center.", "Black captures.",
    "The knight centralizes and eyes the key e6-square.",
    "The king steps forward into the dangerous part of the board.",
    "The knight occupies a powerful outpost and restricts the black position.",
    "Black brings a rook across to seek counterplay.",
    "The queen turns toward the attack and eyes g7 and d7.", "Black defends.",
    "The knight checks and starts the king chase.", "The king moves back in the selected line.",
    "White sacrifices the rook with check. Taking it would allow a different mating continuation, so the rook cannot be touched safely.",
    "Black declines the capture and moves the king.",
    "The rook checks again from f7 and remains untouchable.", "The king moves.",
    "The rook shifts sideways with check and continues the forcing sequence.",
    "The king is driven into the corner.",
    "The rook captures the pawn with check. The historical game is remembered for this relentless sequence; the players' later actions are part of the story, not a forced chess move.",
  ),
  "fischer_spassky72": E(
    "A Game for the Crown", "Bobby Fischer", "Boris Spassky", "Queen's Gambit (Tartakower variation)",
    "Played during the Cold War match for the world title, this was one of Fischer's finest games. He begins with 1.c4 rather than his usual 1.e4, builds quietly, then opens the center and converts the accumulated advantages.",
    "A game can be won without a spectacular sacrifice. Build small advantages—better piece placement, weak pawns, and open lines—then open the center when the position is ready.",
    "Fischer begins with c4 instead of his usual e4, also sidestepping some preparation.",
    "Black responds in a classical way.", "White develops flexibly.", "Black claims the center.",
    "White joins the d4 structure and reaches a Queen's Gambit position.", "Natural development.",
    "White develops another piece.", "Black prepares to castle.",
    "The bishop pins the f6-knight and adds pressure.", "Black castles.",
    "White supports the center and opens the bishop's diagonal.",
    "Black asks the bishop to choose a square.", "The bishop keeps the pin.",
    "The Tartakower setup prepares to develop the bishop on the long diagonal.",
    "White exchanges in the center.", "Black recaptures and works to remove the pin.",
    "White continues the exchange.", "The queen recaptures.",
    "White exchanges again.",
    "Black recaptures with the pawn, leaving d5 as a potential long-term weakness.",
    "The rook occupies the open c-file and eyes c7 and c5.", "The bishop supports d5.",
    "The queen becomes active and eyes a6 and c6.",
    "Black expands in the center and seeks counterplay.",
    "The queen changes direction and targets c5.", "The rook joins the c-file.",
    "The bishop adds pressure.", "Black attacks the bishop.",
    "White exchanges in the center.", "Black recaptures, leaving the pawns less coordinated.",
    "White castles and brings the remaining pieces into the game.",
    "Black is forced into a cramped defensive position.",
    "The bishop retreats calmly and prepares the next plan.", "Black rearranges the pieces.",
    "The knight centralizes and attacks the bishop on e6.", "Black defends.",
    "White exchanges and removes another defender.",
    "Black recaptures, but weak e6 and d5 pawns remain together.",
    "White opens the center with the key move of the game, targeting the weak pawns and king at once.",
    "Black pushes the center to hold.", "White advances the other pawn and increases the pressure.",
    "Black reorganizes the defense.", "White closes the center and restricts Black's pieces.",
    "Black searches for counterplay.", "The bishop reaches its strongest diagonal and attacks e6.",
    "Black moves the king away.", "The queen joins the attack and eyes e6 and h6.",
    "Black defends as well as possible.",
    "White makes a quiet improving move and removes a potential weakness.",
    "Black tries to counterattack but has little activity.",
    "White pushes the f-pawn and opens the next attacking route.", "Black captures in the selected line.",
    "The rook recaptures and turns the f-file into an open highway.",
    "Black's pieces are driven into passive defense.",
    "The other rook joins; every white piece now points toward the king.",
    "Black looks for a defensive square.", "The queen improves its position.",
    "Black keeps trying to hold the line.", "The h-pawn joins the encirclement.",
    "Black can only defend.", "White drives the pawn deeper into the position.",
    "Black moves the rook to block.", "The queen reaches the central crossing point of the attack.",
    "Black has no useful active move.", "White secures the flank and removes counterplay.",
    "Black shuffles the queen.", "White calmly coordinates the rooks.",
    "Black shuffles again.", "The second rook improves; White keeps passing the move back.",
    "Black returns the queen.", "The bishop turns toward the h7-knight and creates the last tactical target.",
    "Black tries to defend.", "The queen attacks h7 and the f-file at once.",
    "The knight is forced to defend.",
    "White sacrifices a rook to remove the final defender around the king.",
    "Black recaptures, leaving the king exposed.",
    "The other rook enters and the attack is decisive.", "The king moves.",
    "The bishop helps control the king's escape squares.", "The king returns to the corner.",
    "The queen delivers the final pressure. Spassky resigns in the selected line; the win was built from small advantages rather than a single flashy sacrifice.",
  ),
  "larsen_spassky": E(
    "The Seventeen-Move Turnaround", "Bent Larsen", "Boris Spassky", "Larsen Opening (1.b3)",
    "A miniature ending after only seventeen moves. White gives up a rook and relies on a single passed pawn, producing an astonishing promotion finish.",
    "Material value is not everything: if a passed pawn cannot be stopped and checks remain available, sacrificing a rook may be the fastest route to victory.",
    "The Larsen Opening develops pressure from the side with an unusual first move.",
    "Black confidently takes the center.", "The bishop occupies the long diagonal and eyes e5.",
    "Develops while defending the pawn.", "White adds pressure from the other side.",
    "Natural development.", "White attacks e5 and gains a tempo.",
    "Black pushes the pawn to drive away the knight and gain central space.",
    "The knight jumps to the center.", "Black attacks the knight and gains time.",
    "White exchanges.", "Black recaptures and opens the d-file for the attack.",
    "White stabilizes the formation.", "The bishop supports e4 and Black's pieces become active.",
    "The queen attacks e4 while improving its position.",
    "The queen connects the pieces and prepares to castle long.",
    "White develops and prepares to castle.",
    "Black castles long, starting the race toward the kingside attack.",
    "White attacks the black pawns but loosens the area around the king.",
    "The knight jumps out and eyes h2 and e3.",
    "White tries to defend, but creates a hole near the king.",
    "The h-pawn begins the assault and tries to open the h-file.",
    "White tries to drive the knight away.",
    "Black continues regardless; allowing the pawn to be captured is part of the plan to open the h-file.",
    "White takes the knight, but Black's attacking idea succeeds.",
    "Black recaptures and leaves a pawn on g3 next to the king.",
    "The rook tries to stop the pawn, but the position only appears safe.",
    "The rook sacrifice opens the route to g2 and is the key tactical idea.",
    "Black accepts the rook in the selected line.",
    "The pawn advances past the rook and cannot be stopped by ordinary means.",
    "The rook moves to control the promotion square.",
    "The queen checks and removes the king's escape squares.",
    "The king moves in the selected variation.",
    "The pawn captures the rook and promotes with check. The rook sacrifice has produced a winning queen and Black resigns.",
  ),
}
