# -*- coding: utf-8 -*-
"""English text for the lessons in lessons_gen.py.

The move sequence remains shared with the Japanese source.  Keeping the
translation keyed by lesson id makes it harder for a wording edit to change
the verified chess line by accident.
"""


def E(title, intro, takeaway, *notes):
    return {"title": title, "intro": intro, "takeaway": takeaway, "notes": list(notes)}


EN = {
  "op_italian": E(
    "Italian Game",
    "One of the oldest and clearest openings. It naturally teaches three opening principles: fight for the center, develop minor pieces, and castle early.",
    "In the opening, prioritize development and the center over grabbing material. Keep an eye on the weakness of f7 and make the bishop and knight work.",
    "White takes space in the center and opens the bishop and queen's diagonals.", "Black also contests the center.",
    "The knight develops with tempo against e5, combining pressure with development.", "The pawn is defended while Black develops a piece.",
    "The bishop eyes the vulnerable f7 square. This move gives the Italian Game its name.", "Black mirrors the idea by eyeing f2.",
    "Preparing d4 to expand in the center and giving the bishop a retreat square.", "Black attacks e4 while developing.",
    "White supports the center and chooses a calm setup.", "Black reinforces the center and prepares for king safety. Both sides have followed sound principles.",
  ),
  "op_ruylopez": E(
    "Ruy Lopez (Spanish Opening)",
    "A major opening that has been played at the highest level for generations. The bishop creates indirect pressure on the knight defending e5, building central control over time.",
    "Do not rush to capture. Build pressure, castle, and then contest the center.",
    "White claims central space.", "Black answers symmetrically.", "The knight attacks e5 while developing.", "Black defends e5 and develops.",
    "The bishop puts indirect pressure on the knight defending e5. The point is pressure, not an immediate capture.",
    "A standard move that asks the bishop to decide where it belongs.", "The bishop retreats while keeping the pressure on the knight.",
    "Black attacks e4 and begins active counterplay in the center.", "White castles early, following a core opening principle.",
    "Black develops and prepares to castle. This is a typical healthy position for both sides.",
  ),
  "op_sicilian": E(
    "Sicilian Defense",
    "Black avoids a symmetrical ...e5 and chooses ...c5 for an unbalanced fight. The sides often attack on different wings, which can lead to sharp play.",
    "Symmetry is not mandatory. Black accepts a different pawn structure to create counterplay on the c-file.",
    "White takes central space.", "Black chooses the Sicilian, using the c-pawn to create an unbalanced position.",
    "Developing while preparing d4.", "Black supports the center and keeps ...Nf6 or ...e5 available.",
    "White opens the center to fight for the initiative.", "Black exchanges and opens the c-file for future activity.",
    "The knight recaptures and occupies a strong central square.", "Black attacks e4 while developing.",
    "The knight supports e4 and completes the basic development setup.", "This is the Najdorf move order: ...a6 prepares ...b5 and controls useful squares.",
  ),
  "op_french": E(
    "French Defense",
    "Black prepares ...d5 with ...e6, building a solid central challenge. The king side is sturdy, but the c8 bishop may need careful planning in a long game.",
    "Absorb the opponent's central pressure, then strike back in the center or on the wings.",
    "White claims the center.", "The French Defense: Black prepares ...d5 against e4.", "White expands in the center.",
    "Black challenges the center as planned.", "The knight supports e4 and adds pressure to d5.",
    "Black attacks e4 and increases the central tension.",
    "The bishop pins the f6 knight to the queen on d8 and reduces the pressure on e4.",
    "Black develops and prepares to break the pin with ...Be7.",
    "White closes the center and gains space. The future attacking directions become clearer.",
    "The knight retreats, readying counterplay with ...c5 or ...f6. Patient defense is typical of the French.",
  ),
  "op_qgd": E(
    "Queen's Gambit Declined",
    "A major opening beginning with d4 rather than e4. The c4 pawn is offered as a gambit, but the point is to gain central influence, not simply to give away material.",
    "Offer a flank pawn to build central pressure. Whether Black accepts or declines, the strategic goal is control of the center.",
    "White takes central space with the queen's pawn.", "Black occupies the center symmetrically.",
    "The c-pawn challenges d5. White offers it in exchange for central pressure.",
    "Black declines the gambit and supports d5 with ...e6.", "White increases pressure on d5 while developing.",
    "Black develops while supporting the center.", "The bishop pins the f6 knight to the queen and indirectly pressures d5.",
    "Black prepares to break the pin.", "White opens the f1 bishop's path and prepares to castle.",
    "Black castles and prepares for a long strategic battle. This is a typical solid setup.",
  ),
  "op_carokann": E(
    "Caro-Kann Defense",
    "Black prepares ...d5 with ...c6. Like the French, it is solid, but the c8 bishop can usually develop outside the pawn chain more easily.",
    "Build a sound center while developing the bishop before it becomes restricted. The result is a balanced, resilient setup.",
    "White takes the center.", "The Caro-Kann: ...c6 prepares ...d5 without blocking the c8 bishop.",
    "White expands in the center.", "Black challenges the center.", "The knight supports e4 and attacks d5.",
    "Black exchanges in the center and clarifies the pawn structure.", "White recaptures with the knight and occupies a good square.",
    "The bishop develops outside the pawn chain before it can become restricted. This is a key Caro-Kann idea.",
    "The knight attacks the bishop and gains a tempo.", "The bishop preserves itself. Black has a solid, playable position.",
  ),
  "cb_fork": E(
    "Knight Fork",
    "A knight can often attack widely separated targets in one move. A fork that checks the king and attacks a major piece is a classic first tactic to learn.",
    "Look for a knight move that gives check while attacking another valuable piece. The opponent must answer the check first, which may leave the other target exposed.",
    "The knight gives check and attacks the queen on c6 at the same time: a fork.", "The king moves; the queen cannot save itself in this line.", "White wins the queen. This is the power of a knight fork.",
  ),
  "cb_pin": E(
    "Using a Pin",
    "A piece is pinned when moving it would expose the king to a line attack. A pinned piece is restricted, but it is not automatically undefended, so always check the whole position.",
    "When you find a pinned piece, verify that it really cannot move and count its defenders before attacking it with a pawn or minor piece.",
    "The knight on d5 is pinned by the rook: moving it would expose the king on d8. White can capture it with the c-pawn.",
  ),
  "cb_skewer": E(
    "Skewer",
    "A skewer is often described as the reverse of a pin: check the more valuable front piece, then take the piece behind it after the king moves.",
    "When a king and a valuable piece line up, look for a checking move that forces the king away and exposes the rear target.",
    "The rook checks along the e-file. The king and queen are lined up behind one another.", "The king moves aside; this line uses Kd5.", "The rook captures the queen behind the king. That is the point of a skewer.",
  ),
  "cb_backrank": E(
    "Back-Rank Mate",
    "A king can look safe behind its own pawns, but those pawns can also remove every escape square. A rook or queen invading the back rank can then deliver mate.",
    "Watch for a king whose pawn shield has not made an escape square. Give your own king luft before the back rank becomes a trap.",
    "The rook invades Black's back rank and checkmates. The pawns on f7, g7, and h7 leave the king no escape.",
  ),
  "cb_double": E(
    "Double Attack (Queen)",
    "Because the queen moves along ranks, files, and diagonals, it can attack two distant targets in one move. A double attack with check is especially forcing.",
    "Before moving the queen, ask whether it can attack two or more targets. A checking double attack deserves particular attention.",
    "The queen gives diagonal check and also attacks the bishop on h4 along the rank.", "The king moves to f8; in this line the bishop is left undefended.", "The queen takes the bishop. It is not check here, but the double attack has won material.",
  ),
  "eg_rook": E(
    "Rook Checkmate: The Basic Position",
    "Checkmating with king and rook is a fundamental endgame skill. The key is to use your king to take away the enemy king's escape squares, often with opposition.",
    "A rook cannot mate by itself. Bring your king in front of the enemy king, remove the escape squares, and use the rook to close the final rank.",
    "The white king on e6 controls d7, e7, and f7, so the rook can deliver mate from the back rank. King and rook must work together.",
  ),
  "eg_tworooks": E(
    "Ladder Mate with Two Rooks",
    "Two rooks can normally checkmate without the king's help by taking away one rank at a time and alternating checks. This is the ladder, or staircase, technique.",
    "Use one rook to seal an escape rank and the other to give check. Repeat the pattern until the enemy king reaches the edge.",
    "The rook on a7 seals the seventh rank, including d7, e7, and f7. The rook on b6 checks from the eighth rank for the ladder mate.",
  ),
  "eg_queen": E(
    "Queen Checkmate: The Basic Position",
    "The queen is powerful, but a queen next to the enemy king must be protected by your king or another piece, or it may simply be captured.",
    "When placing the queen next to the king, make sure your king protects it. Also watch for stalemate when removing escape squares.",
    "The queen moves next to the king and gives mate. The king on g6 protects g7, so the black king cannot capture the queen.",
  ),
  "eg_promote": E(
    "Promoting a Passed Pawn",
    "A passed pawn with no opposing pawn in front of it can promote on the last rank. If the enemy king is too far away, the pawn can become a decisive new piece.",
    "In the endgame, a pawn that can promote is extremely valuable. Use the rule of the square to see whether the king can catch it.",
    "The pawn reaches the last rank and promotes to a queen. The king on g7 is too far away to stop it; the queen and king can now finish the game.",
  ),
  "op_scotch": E(
    "Scotch Game",
    "White challenges the center immediately on move three. It is a clear, active opening for experiencing open lines and quick development.",
    "Play d4 early to open lines. When a bishop attacks your knight, use the tempo to reposition and keep developing.",
    "White takes central space.", "Black answers symmetrically.", "The knight attacks e5 while developing.", "The knight protects the pawn and develops.",
    "White opens the center at once and fights for the initiative.", "Black exchanges in the center.", "White recaptures with the knight and establishes it in the center.",
    "The bishop attacks the knight and gains a tempo.", "The knight retreats while attacking the bishop in return.", "The bishop keeps its diagonal and retreats calmly; both sides have active pieces.",
  ),
  "op_scandinavian": E(
    "Scandinavian Defense",
    "Black challenges and exchanges the central pawn immediately on move two. The early queen move is a useful way to learn why moving the queen too often can cost tempi.",
    "An early queen sortie can let the opponent gain tempi. Black accepts that trade-off for a clear, solid structure.",
    "White takes central space.", "The Scandinavian: Black immediately challenges the e-pawn.", "White captures in the center.",
    "Black recaptures with the queen, accepting that the early queen may be chased.", "The knight develops with tempo against the queen.",
    "The queen steps away to a useful square.", "White builds a broad center and develops.", "Black develops a knight and prepares counterplay.",
    "White develops naturally.", "...c6 gives the queen useful squares and supports a solid setup.",
  ),
  "op_kingsindian": E(
    "King's Indian Defense",
    "Black allows White a broad center, then plans counterplay with the fianchettoed bishop and ...e5 or ...f5. It teaches a flexible approach instead of fighting for every central square immediately.",
    "A temporary concession of the center can be acceptable if you have a concrete counterstrike. Castle early and prepare the break with purpose.",
    "White claims central space with the queen's pawn.", "The knight controls e4 and develops.", "White expands with c4.",
    "Black prepares the bishop's fianchetto on g7.", "White supports the center while developing.", "The bishop takes the long diagonal, the signature piece of the King's Indian.",
    "White occupies the center confidently.", "Black supports the center and prepares ...e5.", "White develops naturally.",
    "Black castles before launching the counterplay.", "White develops and prepares to castle.", "Black finally strikes in the center with ...e5.",
  ),
  "op_english": E(
    "English Opening",
    "The English begins with 1.c4 instead of the immediate e4 or d4. The position can resemble a reversed Sicilian, with White having an extra tempo to build patiently.",
    "The first move need not be e4 or d4. Use c4 to pressure the center from the side and build a good position with a fianchetto.",
    "The English pressures d5 and e4 from the side.", "Black occupies the center, creating a reversed-Sicilian structure.", "The knight develops and eyes d5.",
    "Black develops symmetrically.", "White develops while putting pressure on e5.", "The knight supports the pawn.",
    "White prepares the bishop's fianchetto; the long diagonal will matter.", "Black expands and counterattacks in the center.",
    "White captures once in the center.", "Black recaptures with the knight. Both sides have developed according to sound principles.",
  ),
  "cb_smother": E(
    "Smothered Mate",
    "A king surrounded by its own pieces can be finished by a knight. This famous pattern sacrifices the queen to force the defending rook into the square needed for the final knight move.",
    "A king boxed in by its own pieces is vulnerable to a knight. Sometimes a queen sacrifice is justified if it creates a forced smothered mate.",
    "The knight checks. The king cannot return to h8 and moves to g8 in this line.", "The king steps away from the corner to g8.",
    "The knight moves and the queen's discovered line to g8 also checks. In a double check, the king must move.",
    "The g8 escape is covered, so the king is pushed back to h8.", "The queen offers itself on g8. The knight on h6 protects that square, so the king cannot take it.",
    "The rook captures the queen, filling the last escape square with its own piece.", "The knight returns for smothered mate: the king is boxed in and cannot capture the knight.",
  ),
  "cb_discovered": E(
    "Discovered Attack",
    "When a front piece moves, it can reveal the line of a piece behind it. If the discovered line gives check while the moving piece attacks something else, the defender may lose the second target.",
    "Look for a piece blocking a rook, bishop, or queen. Moving it may reveal check and create a second attack at the same time.",
    "The knight moves, revealing the rook's check along the e-file. The knight also attacks the queen on d8.",
    "The king moves to f8 to answer the check, leaving the queen under attack.",
    "The knight takes the queen. With the king on f8, the rook on h8 cannot recapture; the discovered attack has worked.",
  ),
  "eg_opposition": E(
    "Promotion with Opposition",
    "In a king-and-pawn ending, king placement is everything. Put your king in front of the pawn and use opposition to push the enemy king away.",
    "A pawn cannot promote safely by itself. Lead with the king, drive the opposing king back, and escort the pawn toward promotion.",
    "The king moves ahead of the pawn and begins to push the enemy king back.", "The black king retreats.", "The pawn advances while protected by the king.",
    "Black holds the opposition from the front.", "The pawn advances again; the king protects it, so Black must give way.",
    "The black king steps aside because it cannot capture the protected pawn.", "The white king approaches the promotion square and clears the path.",
    "Black is too late to stop the pawn.", "The pawn promotes under the king's escort.",
  ),
  "cb_doublecheck": E(
    "Double Check",
    "A double check occurs when two pieces check at once. Blocking one line or capturing one checker is not enough; the king must move.",
    "When a knight move opens a rook or bishop line, check whether the move also checks with the knight. Double check can force the king away from a valuable piece.",
    "The knight checks and opens the rook's c-file check at the same time. That is a double check.", "The king must move; blocking or capturing one checker cannot solve both checks.", "The knight captures the exposed rook. The double check gave it time to do so.",
  ),
  "cb_epaulette": E(
    "Epaulette Mate",
    "When a king's own rooks occupy both neighboring squares, a queen can sometimes mate from the front. The king's own pieces become its prison.",
    "Look for escape squares blocked by the opponent's own pieces. If both sides are sealed, a frontal check may be decisive.",
    "The queen checks from the front. The rooks block both sides, while the queen covers the diagonal and forward escapes.",
  ),
  "cb_anastasia": E(
    "Anastasia's Mate",
    "A rook and knight coordinate to mate a king near the edge. The knight covers the escape squares while the rook checks from the side.",
    "The knight on e7 controls g8 and g6. Once the king is on the edge, bring the rook across the h-file.",
    "The rook reaches the h-file and checks. The knight covers g6 and g8, while the rook controls the h-file escapes.",
  ),
  "eg_breakthrough": E(
    "Pawn Breakthrough",
    "Even three pawns against three can create a passed pawn if they advance in the right order. The goal is to open a breakthrough rather than to win every exchange immediately.",
    "Start with the central pawn, but calculate the opponent's choice. This line follows ...cxb6; ...axb6 requires a different order.",
    "The central pawn offers itself. Both a7 and c7 can capture, so the breakthrough order depends on Black's reply.", "This line follows ...cxb6. If ...axb6 is played, the continuation changes.",
    "The other wing pawn advances and attacks b7.", "Here Black recaptures with b7, opening the c-file for the last pawn.",
    "The remaining c-pawn becomes a passed pawn. The king is too far away in this line.", "The king chases the pawn, but it is already too late.",
    "The pawn keeps running.", "The king cannot catch it.", "The pawn promotes. The breakthrough created a queen from an equal pawn mass.",
  ),
  "eg_square": E(
    "The Rule of the Square",
    "You can often tell whether a king can catch a passed pawn by imagining a square from the pawn to its promotion rank. A king inside the square can catch it; a king outside cannot, assuming no other tactics intervene.",
    "Visualize the pawn's square. If the opposing king is outside it, the pawn may promote by running straight ahead.",
    "The pawn advances. The black king is outside the square and cannot catch it.", "The king tries to approach.", "The pawn continues forward.",
    "The king follows, but is still too slow.", "One step from promotion.", "The king finally approaches, but not in time.", "The pawn promotes first: outside the square means no catch.",
  ),
  "op_kingsgambit": E(
    "King's Gambit",
    "White offers a pawn on move two to open the center and attack quickly. This line uses the declined variation, showing that Black need not accept the pawn.",
    "A pawn offer does not have to be accepted. Prioritize the center and piece activity; a solid development plan can meet the gambit.",
    "White takes central space.", "Black answers symmetrically.", "White offers the f-pawn to open lines and attack.",
    "Black declines and develops the bishop to a useful diagonal aimed at f2.", "White develops and attacks e5.",
    "Black supports the center and gives the bishop a retreat square.", "White develops another piece.", "Black develops while watching e4.",
    "White also places the bishop on the f7 diagonal.", "Black develops naturally while both sides prepare for king safety.",
  ),
  "op_vienna": E(
    "Vienna Game",
    "White develops the knight on move two and keeps the option of f4. It is a flexible way to develop before deciding how to challenge the center.",
    "Changing the move order can make the opponent's choices harder. Develop first, then use f4 when the position supports it.",
    "White takes central space.", "Black answers symmetrically.", "The Vienna move: develop the knight and keep f4 in reserve.",
    "Black develops and eyes e4.", "White now commits to f4 and opens a central fight.", "Black counterattacks in the center with ...d5.",
    "White captures the e5 pawn.", "Black recaptures with the knight and centralizes it.", "White develops while supporting e5.", "Black develops and prepares to castle; a playable middlegame is coming.",
  ),
  "op_petrov": E(
    "Petrov Defense",
    "When White attacks e5, Black attacks e4 in return. The result is symmetrical and solid, making it a useful lesson in meeting an attack with counterplay.",
    "You do not always have to defend passively. A direct counterattack can restore balance while keeping the position coordinated.",
    "White claims the center.", "Black answers symmetrically.", "The knight attacks e5 while developing.", "Black attacks e4 instead of defending e5: the Petrov idea.",
    "White takes the pawn.", "Black first drives the knight away rather than recapturing immediately.", "The knight retreats.",
    "Black now recaptures; the pawn count is equal again.", "White expands in the center.", "Black contests the center and gives the knight a stable base.",
  ),
  "cb_boden": E(
    "Boden's Mate",
    "Two bishops can cross their diagonals to trap a king. One gives the check while the other covers the escape squares, often against a king boxed in on the queenside.",
    "Look for crossing bishop diagonals and escape squares blocked by the defender's own pieces. Two bishops can be enough when the net is complete.",
    "The bishop checks along a6-c8. The second bishop covers b8 and c7; d7 and d8 are occupied by Black's own pieces, so it is mate.",
  ),
  "cb_decoy": E(
    "Decoy",
    "A decoy lures an enemy piece, often the king, onto a square where a tactic works. This example uses a check to invite the king toward a knight fork.",
    "Find the square where the fork works first. Then look for a forcing check that encourages the king to go there. The opponent may have alternatives, so calculate them.",
    "The bishop checks. The bishop controls f7 and the rook occupies f8; this line follows the king's retreat to h8.", "The king goes to the corner and enters the knight's tactical net.",
    "The knight checks and attacks the queen on d8 at the same time.", "This line follows Kg8. Black can also try Rxf7, so the fork depends on the opponent's reply.",
    "The knight takes the queen with check, also opening the bishop's line to the king.",
  ),
  "eg_underpromo": E(
    "Underpromotion to a Knight",
    "A queen is not always the best promotion. Promoting to a knight can give check and create a fork that a queen would miss.",
    "When promoting, compare every legal piece. The goal is the piece that solves the position, not automatically the strongest piece.",
    "The pawn promotes to a knight with check and forks the queen on d6.", "The king moves to answer the check.", "The new knight captures the queen. A queen promotion would not create this fork.",
  ),
  "eg_connected": E(
    "Connected Passed Pawns",
    "Two adjacent passed pawns are powerful because they can protect one another. If the opposing king is too far away, they can advance as a team and promote.",
    "Advance connected passed pawns as a unit: one moves while the other supports it. Keep moving before the enemy king arrives.",
    "The front pawn advances. The b6 pawn protects c7, so the king cannot take it.", "The king chases, but is too far away.", "The rear pawn advances; both pawns are now one step from promotion.",
    "The king is too late.", "The front pawn promotes while the two pawns support one another.",
  ),
  "cb_hanging": E(
    "Hanging Pieces: The Basic Habit",
    "The most basic tactical question is whether the opponent's pieces are defended. A piece with no defenders may be hanging and can often be won for free.",
    "Before every move, scan for undefended enemy pieces. Then verify that your capture is safe before taking.",
    "The rook on a5 has no defender. The queen can take it, winning a full rook. Spotting this consistently matters more than flashy combinations.",
  ),
  "cb_deflection": E(
    "Deflection",
    "Deflection makes a defender abandon one of its duties. The rook on e7 protects both the f7 pawn and the e-file, so forcing it to handle one duty can expose the other.",
    "Look for an overloaded defender. A sacrifice can force it to leave one assignment, allowing the real threat to succeed.",
    "The queen enters on f7. The bishop on c4 protects f7, so the king cannot take the queen.", "This line follows Rxf7. The rook has now left the e-file to capture.", "The rook enters on e8 with mate after the defender has been deflected.",
  ),
  "cb_windmill": E(
    "Windmill",
    "A windmill repeats discovered checks and captures in a cycle. The rook moves out of the bishop's line, checks are answered, and the rook returns to take another piece.",
    "When a piece blocks a bishop or rook, consider a discovered check. Repeat check, capture, and check when the position allows it; do not assume every reply is forced.",
    "The rook captures on c7 and reveals the bishop's check. Black has several replies; this line chooses Kg8.", "The h7 pawn blocks the corner, so the king escapes to g8 in this line.",
    "The rook returns with check. The bishop protects it, so the king moves away.", "The king is pushed back to h8.",
    "The windmill turns again: the rook captures b7 while revealing another discovered check. Other defenses exist, but this line repeats the pattern.",
    "The king escapes to g8 again.", "The rook returns with another check and continues harvesting material.", "The king goes back to the corner.",
    "The rook moves to the fifth rank, revealing the bishop's check and attacking the queen on a5.",
    "This line interposes the queen on e5 to stop the diagonal check.", "The rook takes the queen. The windmill ends after using checks to win material.",
  ),
  "eg_stalemate": E(
    "Watch for Stalemate",
    "Stalemate is the classic way to turn a winning position into a draw. If the side to move is not in check and has no legal move, the game is drawn.",
    "Before the final move, check that the opponent still has a legal move. Remove escape squares while giving check when possible. Qg6? here would stalemate.",
    "The queen moves next to the king and gives mate. The king on f7 protects g7. Qg6 instead would leave Black with no move but no check: stalemate.",
  ),
  "eg_lucena": E(
    "Lucena Position: Building a Bridge",
    "The Lucena position is a key winning method in rook-and-pawn versus rook endings. Use your rook as a bridge to shelter the king from checks and promote the pawn.",
    "Prepare the rook on the fourth rank. When checks arrive, place that rook in front of your king as a protected bridge, then promote.",
    "The rook goes to the fourth rank to prepare the bridge.", "Black waits.", "The king steps away from the pawn and clears the promotion route.",
    "Black starts checking from behind.", "The king advances while avoiding the check.", "Another check.",
    "The king reaches d5, where it protects the rook on f4.", "Black checks again.",
    "The rook builds the bridge on d4. The king on d5 protects it, so the check can be stopped.", "Black captures the bridge.",
    "The king recaptures and removes the checking rook.", "Black's king hurries back, but it is too late.", "The pawn promotes with check. The bridge has converted the Lucena position.",
  ),
  "eg_philidor": E(
    "Philidor Position: The Drawing Defense",
    "The Philidor position is a vital drawing method in rook endings. The defending rook controls the rank in front of the enemy king, then checks from behind once the pawn advances.",
    "Keep the rook on the checking rank while the king is in front. When the pawn advances, move behind it and give checks from a distance.",
    "The rook reaches the sixth rank. It prevents the white king from making a direct advance and invites the pawn to move.", "White advances the pawn, but this helps the defensive plan.",
    "The rook moves behind the pawn. The checking sequence begins.", "The white king tries to advance.", "The rook checks from behind.", "The king steps away, but the checks continue.",
    "Another check.", "The king tries another route.", "The checking rook shifts again.", "The king has no shelter that ends the checks.",
    "The rook keeps checking, so White cannot make progress. The lost position is held to a draw.",
  ),
  "cb_zwischenzug": E(
    "Zwischenzug (In-Between Move)",
    "Capturing back immediately is not always best. A zwischenzug inserts a stronger move first, often a check, before making the expected recapture.",
    "Pause before recapturing. Ask whether a check or major threat can come first; changing the order can win an extra pawn.",
    "Instead of immediately playing Nxd5, Black inserts a check with Bxh2+. The opponent must answer the check first.", "This line naturally recaptures the bishop with Kxh2; Kh1 and Kf1 are also legal responses.",
    "Black now recaptures on d5. The in-between check has won the h2 pawn as an extra.", "White recaptures as well. The pieces are balanced, but Black has won one extra pawn by changing the order.",
  ),
  "cb_interference": E(
    "Interference",
    "Interference places a piece between a defender and its target, cutting the line of protection. The defender remains on the board but can no longer do its job.",
    "Trace the exact line by which a piece is defended. If you can occupy a square on that line, the target may become vulnerable.",
    "The pawn advances to c7 and blocks the seventh-rank line. The rook on a7 can no longer defend the bishop on e7; the pawn is protected by d6.",
    "This line follows Rxc7, capturing the interfering pawn.", "The d-pawn recaptures, winning the rook and reaching c7 near promotion.",
    "The bishop moves to d8 to stop promotion.", "The pawn captures the bishop while promoting. The interference started the entire tactic.",
  ),
  "eg_wrongbishop": E(
    "Wrong-Colored Bishop: A Draw",
    "A bishop and pawn do not always win. With a rook pawn, if the bishop cannot control the promotion square's color, the defending king can hold the corner and draw.",
    "Check the color of the promotion square. If your bishop cannot attack that color, the defender may draw simply by reaching the corner.",
    "The king approaches, trying to drive the defender away.", "The black king circles near the corner. h8 is a dark square, which the white light-squared bishop cannot attack.",
    "The pawn advances with check.", "The king returns to h8, the safe corner. White has no way to force it out.",
    "The king approaches again, but this move stalemates Black. With the correct-colored bishop, this ending would be won.",
  ),
  "eg_triangulation": E(
    "Triangulation",
    "Sometimes the winning idea is to give the opponent the move in the same position. A king can spend one extra tempo by walking a triangle and return with the move transferred.",
    "A three-move triangle returns the king to its starting square. That spare tempo can create zugzwang when the opposing king has no useful waiting move.",
    "The first step of the triangle deliberately takes the long way around.", "This line returns Black's king to d7; Black also has alternatives such as ...Ke6 and ...Kf7, so calculate the opponent's best defense.",
    "The second triangle step.", "Black's king returns.", "The white king completes the triangle. The main piece placement is restored, but it is now Black to move: the zugzwang idea.",
    "Black must move and leaves d6 uncovered.", "The white king enters through the opening and clears the promotion route.", "Black cannot catch the pawn.",
    "The pawn advances under the king's protection.", "Black's king rushes forward.", "The pawn advances again; the extra tempo decides the ending.",
  ),
}
